In [161]:
import pandas as pd
import numpy as np
from pycaret.classification import load_model, predict_model
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import joblib

gw=6

## Features

In [128]:
cs_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty',  'ownership_change', 'percenatge_net_transfers',
            'clean_sheets',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_5',  'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

y_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',

                'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

xg_features = [ 'position',  'xG', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1',  'goals_scored_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3',  'goals_scored_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5',  'goals_scored_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

xa_features = [ 'position',  'xA', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence',
                 'creativity', 'threat','starts',

            'expected_assists_1', 'expected_goal_involvements_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1',  'shots_1','xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_3', 'expected_goal_involvements_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'shots_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_5', 'expected_goal_involvements_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'shots_5',  'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

saves_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',
            'saves',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',


            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

xgc_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty',  'ownership_change', 'percenatge_net_transfers',

            'expected_goals_conceded',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1', 'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_3',  'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',


            'clean_sheets_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

# Utils

In [154]:
def calc_xP_pred(row):
    # Minutes played bonus
    if row['minutes_3'] >= 60:
        minutes_bonus = 2
    elif row['minutes_3'] > 0:
        minutes_bonus = 1
    else:
        minutes_bonus = 0  # if player didn't play at all
    if row['position'] == '1':

        ## GK
        ## ---> >60  = 2
        ## ---> cs*4
        ## ---> ((sv)/3)*1
        ## ---> (gc/2)*-1
        ## ---> yc*-1
        return (
            minutes_bonus +
            4 * row['cs_preds'] +
            1 * round(row['saves_preds']/3, 3) -
            1 * round(row['xgc_preds']/2, 3) -
            1 * row['y_preds']
        )

    elif row['position'] == '2':
        ## DEF
        ## ---> >60  = 2
        ## ---> xg*6
        ## ---> xa*3
        ## ---> cs*4
        ## ---> gc
        ## ---> yc*-1


        return (
            minutes_bonus +
            6 * row['xg_preds'] +
            3 * row['xa_preds'] +
            4 * row['cs_preds'] -
            1 * round(row['xgc_preds']/2, 3) -
            1 * row['y_preds']
        )
    elif row['position'] == '3':
        ## MID
        ## ---> >60  = +2
        ## ---> xg*5
        ## ---> xa*3
        ## ---> cs*1
        ## ---> yc*-1

        return (
            minutes_bonus +
            5 * row['xg_preds'] +
            3 * row['xa_preds'] +
            1 * row['cs_preds'] -
            1 * row['y_preds']
        )
    elif row['position'] == '4':
        ## FWD
        ## ---> >60  = 2
        ## ---> xg*4
        ## ---> xa*3
        ## ---> yc*-1
        # print(row['fpl_name'], row['position'], minutes_bonus +
        #     4 * row['xg_preds'] +
        #     3 * row['xa_preds'] -
        #     1 * row['y_preds'])
        return (
            minutes_bonus +
            4 * row['xg_preds'] +
            3 * row['xa_preds'] -
            1 * row['y_preds']
        )
    else:
        return 0  # fallback for unknown positions

## Load Models

### Classification Models

In [132]:
# Cleansheet models
g_cs_model = load_model('../gk_cs_model')
def_cs_model = load_model('../def_cs_model')
mid_cs_model = load_model('../mid_cs_model')

# Yellow card models
g_y_model = load_model('../gk_y_model')
def_y_model = load_model('../def_y_model')
mid_y_model = load_model('../mid_y_model')
fwd_y_model = load_model('../fwd_y_model')

Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded

### Regression Models

In [133]:
# Expected goal models
def_xg_model = load_model('../def_xg_final_model')
pt_def_xg = joblib.load('../pt_def_xg.pkl')  # Load fitted transformer

mid_xg_model = load_model('../mid_xg_final_model')
pt_mid_xg = joblib.load('../pt_mid_xg.pkl')  # Load fitted transformer

fwd_xg_model = load_model('../fwd_xg_final_model')
pt_fwd_xg = joblib.load('../pt_fwd_xg.pkl')  # Load fitted transformer


# Expected assist models
def_xa_model = load_model('../def_xa_final_model')
pt_def_xa = joblib.load('../pt_def_xa.pkl')  # Load fitted transformer

mid_xa_model = load_model('../mid_xa_final_model')
pt_mid_xa = joblib.load('../pt_mid_xa.pkl')  # Load fitted transformer

fwd_xa_model = load_model('../fwd_xa_final_model')
pt_fwd_xa = joblib.load('../pt_fwd_xa.pkl')  # Load fitted transformer


# Goalkeeper save models
gk_saves_model = load_model('../g_saves_final_model')
pt_gk_saves = joblib.load('../pt_gk_saves.pkl')  # Load fitted transformer


# Expected goal conceded models
gk_xgc_model = load_model('../g_xgc_final_model')
pt_gk_xgc = joblib.load('../pt_gk_xgc.pkl')  # Load fitted transformer

def_xgc_model = load_model('../def_xgc_final_model')
pt_def_xgc = joblib.load('../pt_def_xgc.pkl')  # Load fitted transformer

Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded

## Current

In [134]:
# Innit
data_25_26 = pd.read_csv('../../data/joint/25-26/merged_player_data.csv')

data = data_25_26[data_25_26['event'] == 6]

data_gk = data[data['position'] == '1']
data_def = data[data['position'] == '2']
data_mid = data[data['position'] == '3']
data_fwd = data[data['position'] == '4']

### Classifiers

In [135]:
data_gk_cs = data_gk[cs_features]
data_def_cs = data_def[cs_features]
data_mid_cs = data_mid[cs_features]

# cs = data_gk_cs[['clean_sheets']].copy()
data_gk_cs.drop(columns=['position', 'clean_sheets'], inplace=True)
data_def_cs.drop(columns=['position', 'clean_sheets'], inplace=True)
data_mid_cs.drop(columns=['position', 'clean_sheets'], inplace=True)

cs_preds_gk = predict_model(g_cs_model, data=data_gk_cs)
cs_preds_def = predict_model(def_cs_model, data=data_def_cs)
cs_preds_mid = predict_model(mid_cs_model, data=data_mid_cs)

cs_preds_gk = cs_preds_gk.rename(columns={'prediction_label': 'cs_preds_trans'})
cs_preds_def = cs_preds_def.rename(columns={'prediction_label': 'cs_preds_trans'})
cs_preds_mid = cs_preds_mid.rename(columns={'prediction_label': 'cs_preds_trans'})

# Add cs_preds to data_gk
data_gk['cs_preds'] = cs_preds_gk[['cs_preds_trans']]
data_def['cs_preds'] = cs_preds_def[['cs_preds_trans']]
data_mid['cs_preds'] = cs_preds_mid[['cs_preds_trans']]

In [146]:
data_gk_y = data_gk[y_features]
data_def_y = data_def[y_features]
data_mid_y = data_mid[y_features]
data_fwd_y = data_fwd[y_features]

# y = data_gk_y[['yellow_cards']].copy()
data_gk_y.drop(columns=['position', 'yellow_cards'], inplace=True)
data_def_y.drop(columns=['position', 'yellow_cards'], inplace=True)
data_mid_y.drop(columns=['position', 'yellow_cards'], inplace=True)
data_fwd_y.drop(columns=['position', 'yellow_cards'], inplace=True)

y_preds_gk = predict_model(g_y_model, data=data_gk_y)
y_preds_def = predict_model(def_y_model, data=data_def_y)
y_preds_mid = predict_model(mid_y_model, data=data_mid_y)
y_preds_fwd = predict_model(fwd_y_model, data=data_fwd_y)

y_preds_gk = y_preds_gk.rename(columns={'prediction_label': 'y_preds_trans'})
y_preds_def = y_preds_def.rename(columns={'prediction_label': 'y_preds_trans'})
y_preds_mid = y_preds_mid.rename(columns={'prediction_label': 'y_preds_trans'})
y_preds_fwd = y_preds_fwd.rename(columns={'prediction_label': 'y_preds_trans'})

# Add y_preds to data_gk
data_gk['y_preds'] = y_preds_gk[['y_preds_trans']]
data_def['y_preds'] = y_preds_def[['y_preds_trans']]
data_mid['y_preds'] = y_preds_mid[['y_preds_trans']]
data_fwd['y_preds'] = y_preds_fwd[['y_preds_trans']]

# data_gk = pd.concat([data_gk, data_def, data_mid, data_fwd])

### Regressors

In [137]:
data_def_xg = data_def[xg_features]
data_mid_xg = data_mid[xg_features]
data_fwd_xg = data_fwd[xg_features]

data_def_xg.drop(columns=['position', 'xG'], inplace=True)
data_mid_xg.drop(columns=['position', 'xG'], inplace=True)
data_fwd_xg.drop(columns=['position', 'xG'], inplace=True)

xg_preds_def = predict_model(def_xg_model, data=data_def_xg)
xg_preds_mid = predict_model(mid_xg_model, data=data_mid_xg)
xg_preds_fwd = predict_model(fwd_xg_model, data=data_fwd_xg)

xg_preds_def = xg_preds_def.rename(columns={'prediction_label': 'xg_preds_trans'})
xg_preds_mid = xg_preds_mid.rename(columns={'prediction_label': 'xg_preds_trans'})
xg_preds_fwd = xg_preds_fwd.rename(columns={'prediction_label': 'xg_preds_trans'})

# Add xg_preds to data_gk
data_def['xg_preds'] = xg_preds_def[['xg_preds_trans']]
data_mid['xg_preds'] = xg_preds_mid[['xg_preds_trans']]
data_fwd['xg_preds'] = xg_preds_fwd[['xg_preds_trans']]

In [138]:
data_def_xa = data_def[xa_features]
data_mid_xa = data_mid[xa_features]
data_fwd_xa = data_fwd[xa_features]

data_def_xa.drop(columns=['position', 'xA'], inplace=True)
data_mid_xa.drop(columns=['position', 'xA'], inplace=True)
data_fwd_xa.drop(columns=['position', 'xA'], inplace=True)

xa_preds_gk = predict_model(def_xa_model, data=data_def_xa)
xa_preds_mid = predict_model(mid_xa_model, data=data_mid_xa)
xa_preds_fwd = predict_model(fwd_xa_model, data=data_fwd_xa)

xa_preds_gk = xa_preds_gk.rename(columns={'prediction_label': 'xa_preds_trans'})
xa_preds_mid = xa_preds_mid.rename(columns={'prediction_label': 'xa_preds_trans'})
xa_preds_fwd = xa_preds_fwd.rename(columns={'prediction_label': 'xa_preds_trans'})

# Add xa_preds to data_gk
data_def['xa_preds'] = xa_preds_gk[['xa_preds_trans']]
data_mid['xa_preds'] = xa_preds_mid[['xa_preds_trans']]
data_fwd['xa_preds'] = xa_preds_fwd[['xa_preds_trans']]

In [139]:
data_gk_saves = data_gk[saves_features]

data_gk_saves.drop(columns=['position', 'saves'], inplace=True)

saves_preds_gk = predict_model(gk_saves_model, data=data_gk_saves)

saves_preds_gk = saves_preds_gk.rename(columns={'prediction_label': 'saves_preds_trans'})

# Add saves_preds to data_gk
data_gk['saves_preds'] = saves_preds_gk[['saves_preds_trans']]

In [140]:
data_gk_xgc = data_gk[xgc_features]
data_def_xgc = data_def[xgc_features]

data_gk_xgc.drop(columns=['position', 'expected_goals_conceded'], inplace=True)
data_def_xgc.drop(columns=['position', 'expected_goals_conceded'], inplace=True)

xgc_preds_gk = predict_model(gk_xgc_model, data=data_gk_xgc)
xgc_preds_def = predict_model(def_xgc_model, data=data_def_xgc)

xgc_preds_gk = xgc_preds_gk.rename(columns={'prediction_label': 'xgc_preds_trans'})
xgc_preds_def = xgc_preds_def.rename(columns={'prediction_label': 'xgc_preds_trans'})
# Add xgc_preds to data_gk
data_gk['xgc_preds'] = xgc_preds_gk[['xgc_preds_trans']]
data_def['xgc_preds'] = xgc_preds_def[['xgc_preds_trans']]

### Combine Data

In [163]:
data_with_preds = pd.concat([data_gk, data_def, data_mid, data_fwd])

# data_with_preds[['fpl_name', 'understat_name', 'team']] = data_with_preds.apply(add_player_name, axis=1, result_type='expand')

data_with_preds['xP_preds'] = data_with_preds.apply(calc_xP_pred, axis=1)

data_with_preds.to_csv(f'./players_preds_{gw}_.csv', index=True)

In [158]:
data_with_preds[data_with_preds['position'] =='1']

,assists_x,bonus,bps,clean_sheets,clearances_blocks_interceptions,creativity,defensive_contribution,element,expected_assists,expected_goal_involvements,...,whh,whd,wha,cs_preds,y_preds,saves_preds,xgc_preds,xg_preds,xa_preds,xP_preds
55,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,...,0.247,0.251,0.502,1.0,0,2.0,2.0,NaN,NaN,5.667
61,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,0.284,0.260,0.456,0.0,0,2.0,2.0,NaN,NaN,1.667
132,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,0.527,0.243,0.231,0.0,0,2.0,2.0,NaN,NaN,1.667
154,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,0.403,0.299,0.299,1.0,0,2.0,2.0,NaN,NaN,5.667
221,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,0.284,0.260,0.456,0.0,0,2.0,3.0,NaN,NaN,1.167
348,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,0.292,0.283,0.425,0.0,0,2.0,2.0,NaN,NaN,1.667
354,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,0.247,0.251,0.502,0.0,0,2.0,2.0,NaN,NaN,1.667
440,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,0.403,0.299,0.299,1.0,0,1.0,1.0,NaN,NaN,5.833
564,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,...,0.636,0.211,0.153,0.0,0,2.0,3.0,NaN,NaN,1.167
715,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,0.794,0.134,0.072,0.0,0,2.0,2.0,NaN,NaN,1.667
827,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,0.511,0.270,0.219,0.0,0,2.0,2.0,NaN,NaN,1.667
861,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,0.636,0.211,0.153,1.0,1,0.0,0.0,NaN,NaN,5.000
921,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,0.323,0.284,0.393,1.0,0,2.0,1.0,NaN,NaN,6.167
1070,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,0.511,0.270,0.219,1.0,0,2.0,1.0,NaN,NaN,6.167
1101,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,0.403,0.299,0.299,0.0,0,0.0,0.0,NaN,NaN,2.000
1127,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,0.794,0.134,0.072,0.0,0,2.0,4.0,NaN,NaN,0.667
1179,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,0.507,0.273,0.221,0.0,0,2.0,3.0,NaN,NaN,1.167
1301,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,0.292,0.283,0.425,0.0,0,2.0,2.0,NaN,NaN,1.667
1467,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,...,0.527,0.243,0.231,1.0,0,2.0,1.0,NaN,NaN,6.167
1473,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,...,0.507,0.273,0.221,0.0,0,2.0,4.0,NaN,NaN,0.667
1519,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,0.636,0.211,0.153,0.0,0,1.0,0.0,NaN,NaN,1.333
1744,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,0.323,0.284,0.393,1.0,0,2.0,2.0,NaN,NaN,5.667

In [166]:
pd.read_csv('./players_preds_6.csv')

,Unnamed: 0,assists_x,bonus,bps,clean_sheets,clearances_blocks_interceptions,creativity,defensive_contribution,element,expected_assists,...,whh,whd,wha,cs_preds,y_preds,saves_preds,xgc_preds,xg_preds,xa_preds,xP_preds
0,55,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,...,0.247,0.251,0.502,1.0,0,2.0,2.0,NaN,NaN,5.667
1,61,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,...,0.284,0.260,0.456,0.0,0,2.0,2.0,NaN,NaN,1.667
2,132,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,...,0.527,0.243,0.231,0.0,0,2.0,2.0,NaN,NaN,1.667
3,154,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,...,0.403,0.299,0.299,1.0,0,2.0,2.0,NaN,NaN,5.667
4,221,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,...,0.284,0.260,0.456,0.0,0,2.0,3.0,NaN,NaN,1.167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,1580,NaN,NaN,NaN,NaN,NaN,9.9,NaN,NaN,NaN,...,0.511,0.270,0.219,NaN,1,NaN,NaN,0.0,0.0,0.000
353,1661,NaN,NaN,NaN,NaN,NaN,67.9,NaN,NaN,NaN,...,0.292,0.283,0.425,NaN,0,NaN,NaN,1.0,1.0,9.000
354,1691,NaN,NaN,NaN,NaN,NaN,13.6,NaN,NaN,NaN,...,0.292,0.283,0.425,NaN,1,NaN,NaN,0.0,0.0,0.000
355,1702,NaN,NaN,NaN,NaN,NaN,5.1,NaN,NaN,NaN,...,0.507,0.273,0.221,NaN,0,NaN,NaN,1.0,0.0,6.000
356,1738,NaN,NaN,NaN,NaN,NaN,10.1,NaN,NaN,NaN,...,0.794,0.134,0.072,NaN,1,NaN,NaN,0.0,0.0,0.000