In [12]:
%run ./clean_data_utils.ipynb
gw = 6

In [9]:
f = pd.read_csv(f'../with new features/data/joint/23-24/merged_player_data.csv')
f[f['fpl_name'] == 'Phil Foden'][['fpl_name', 'event', 'position', 'total_points']]

        fpl_name  event position  total_points
8975  Phil Foden      1      MID             3
8976  Phil Foden      2      MID             9
8977  Phil Foden      3      MID             4
8978  Phil Foden      4      MID             5
8979  Phil Foden      5      MID             2
8980  Phil Foden      6      MID            11
8981  Phil Foden      7      MID             2
8982  Phil Foden      8      MID             2
8983  Phil Foden      9      MID             2
8984  Phil Foden     10      MID             7
8985  Phil Foden     11      MID             6
8986  Phil Foden     12      MID             2
8987  Phil Foden     13      MID             2
8988  Phil Foden     14      MID             9
8989  Phil Foden     15      MID             3
8990  Phil Foden     16      MID             2
8991  Phil Foden     17      MID             5
8992  Phil Foden     19      MID             8
8993  Phil Foden     20      MID            12
8994  Phil Foden     21      MID             2
8995  Phil Foden     22      MID             6
8996  Phil Foden     23      MID            20
8997  Phil Foden     24      MID             3
8998  Phil Foden     25      MID             2
8999  Phil Foden     18      MID             3
9000  Phil Foden     26      MID            11
9001  Phil Foden     27      MID            15
9002  Phil Foden     28      MID             2
9003  Phil Foden     30      MID             3
9004  Phil Foden     31      MID            20
9005  Phil Foden     29      MID            16
9006  Phil Foden     36      MID             5
9007  Phil Foden     37      MID             9
9008  Phil Foden     34      MID             2
9009  Phil Foden     38      MID            15

### Merge FPL and Understat data

In [11]:
# merge_fpl_understat_data("./data/vaastav/data/2022-23/players/", "./data/vaastav/data/2022-23/understat/", "22-23")
merge_fpl_understat_data("./data/vaastav/data/2023-24/players/", "./data/vaastav/data/2023-24/understat/", "23-24")
# merge_fpl_understat_data("./data/vaastav/data/2024-25/players/", "./data/vaastav/data/2024-25/understat/", "24-25")

successfully cleaned 2023-24 fpl data

### Adding fixture difficulty

In [7]:
# add_difficulty('22-23')
add_difficulty('23-24')

====> Starting to add difficulty features to 2023-24

### Add Expected points

In [8]:
# add_xP('22-23')
add_xP('23-24')

================> starting to add xp for season 2023-24

### Add rolling averages

In [9]:
# add_rolling_avgs('22-23')
add_rolling_avgs('23-24')

================> starting to roll by 2 for season 2023-24
<<<<================ Done rolling season 2023-24

### Add owenership_change

In [10]:
# owenership_change('22-23')
owenership_change('23-24')

================> starting to add ownership change for season 2023-24

### Add odds

In [11]:
# odds('22-23')
odds('23-24')

================> starting adding odds for sns 2023-24

### Merge seasons data

In [12]:
# merge_files('22-23')
merge_files('23-24')

starting to merge files for 2023-24
632

In [18]:
import pandas as pd
FPL_teams_23_24 = ['West Ham United', 'Manchester United', 'Everton', 'Bournemouth',
       'Brighton and Hove Albion', 'Crystal Palace', 'Fulham', 'Luton',
       'Tottenham Hotspur', 'Newcastle United', 'Aston Villa',
       'Liverpool', 'Chelsea', 'Sheffield United', 'Nottingham Forest',
       'Burnley', 'Arsenal', 'Manchester City', 'Wolverhampton Wanderers',
       'Brentford']

players_23_24 = pd.read_csv('./data/joint/23-24/merged_player_data.csv')

# set(players_23_24[['player_team']].values.flatten()) #.tolist()

players_23_24[players_23_24['player_team'].isin(FPL_teams_23_24)]

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,npxG_5,xGChain_5,xGBuildup_5,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha
0,0,0,0,0,0.0,127,0.0,0.0,0.0,0.00,...,NaN,NaN,NaN,NaN,0.0,-1.000000,0.0,0.441,0.271,0.288
1,0,0,0,0,0.0,127,0.0,0.0,0.0,0.00,...,0.0,0.00,0.00,0.00,-108.0,-1.000000,0.0,0.506,0.260,0.234
2,0,0,0,0,0.0,127,0.0,0.0,0.0,0.00,...,0.0,0.00,0.00,0.00,-314.0,-1.000000,0.0,0.565,0.236,0.199
3,0,0,0,0,0.0,127,0.0,0.0,0.0,0.00,...,0.0,0.05,0.04,0.00,-15.0,-1.000000,0.0,0.382,0.265,0.353
4,0,0,0,0,0.0,127,0.0,0.0,0.0,0.00,...,0.0,0.05,0.04,0.00,-23.0,-1.000000,0.0,0.577,0.212,0.212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11341,0,2,28,1,0.0,687,0.0,0.0,0.0,1.54,...,0.0,0.13,0.13,2.70,0.0,0.784761,7.0,0.438,0.248,0.314
11342,0,0,31,1,0.0,687,0.0,0.0,0.0,1.04,...,0.0,0.13,0.13,3.78,78921.0,0.819526,6.0,0.577,0.212,0.212
11343,0,0,12,0,0.0,687,0.0,0.0,0.0,1.62,...,0.0,0.17,0.17,4.44,343317.0,0.928148,1.0,0.278,0.249,0.473
11344,0,0,14,0,0.0,687,0.0,0.0,0.0,1.24,...,0.0,0.07,0.07,5.36,0.0,0.928148,2.0,0.284,0.235,0.481
11345,0,0,18,0,0.0,687,0.0,0.0,0.0,2.15,...,0.0,0.20,0.20,6.52,-25381.0,0.308964,3.0,0.653,0.189,0.158

In [23]:
players_23_24 = players_23_24[players_23_24['player_team'].isin(FPL_teams_23_24)]
players_23_24
print(len(set(players_23_24[['player_team']].values.flatten())))

players_23_24.to_csv('./data/joint/23-24/merged_player_data.csv')

20

### Latest working season

In [ ]:
merge_fpl_understat_data("./data/vaastav/data/2023-24/players/", "./data/vaastav/data/2023-24/understat/", "23-24")
add_difficulty('23-24')
add_xP('23-24')
add_rolling_avgs('23-24')
owenership_change('23-24')
odds('23-24')
merge_files('23-24')

%run .

successfully cleaned 2023-24 fpl data

In [6]:
data_23_24 = pd.read_csv('./data/joint/23-24/merged_player_data.csv') # data/joint/23-24/merged_player_data.csv')
data_23_24[data_23_24['round'] == 37][['fpl_name', 'event', 'position', 'total_points']]

                       fpl_name  event position  total_points
5                Aaron Connolly     37      FWD             0
16              Aaron Cresswell     37      DEF             1
65            Aaron Wan-Bissaka     37      DEF             2
96           Abdoulaye Doucouré     37      MID             8
157                  Adam Smith     37      DEF             6
...                         ...    ...      ...           ...
10946           Youri Tielemans     37      MID             8
10962  Youssef Ramalho Chermiti     37      FWD             1
10990             Yves Bissouma     37      MID             2
11024              Zeki Amdouni     37      FWD             1
11045            Đorđe Petrović     34       GK             2

[323 rows x 4 columns]

In [108]:
fpl_player_data = m.rename(columns={'kickoff_time': 'date'})
# change the formats: From 2021-10-03T13:00:00Z to 2021-10-03
fpl_player_data.date = fpl_player_data.date.apply(lambda x: x.split('T')[0])

# Dates are of the form 2021-10-03T13:00:00Z
fpl_dates_min = fpl_player_data['date'].min()
fpl_dates_max = fpl_player_data['date'].max()

# Filter out player info not in the range of dates we are dealing with
understat_filtered = fpl_player_data[(pd.to_datetime(fpl_player_data['date']) >= pd.to_datetime(fpl_dates_min))
                                            & (pd.to_datetime(fpl_player_data['date']) <= pd.to_datetime(fpl_dates_max) )]

# Marge fpl_player_data with m_u if the dates match
player_data_merged = fpl_player_data.merge(understat_filtered, on="date")
player_data_merged

,assists_x,bonus_x,bps_x,clean_sheets_x,creativity_x,element_x,expected_assists_x,expected_goal_involvements_x,expected_goals_x,expected_goals_conceded_x,...,total_points_y,transfers_balance_y,transfers_in_y,transfers_out_y,value_y,was_home_y,yellow_cards_y,fpl_id_y,position_y,team_y
0,0,0,26,1,0.9,18,0.00,0.00,0.00,0.47,...,6,0,0,0,60,True,0,18,NaN,NaN
1,0,0,24,1,1.2,18,0.01,0.01,0.00,1.28,...,6,-54391,71155,125546,60,False,0,18,NaN,NaN
2,0,0,10,0,1.3,18,0.01,0.01,0.00,1.83,...,2,16354,186343,169989,60,True,0,18,NaN,NaN
3,0,0,22,1,0.4,18,0.01,0.01,0.00,0.74,...,5,-294232,95758,389990,60,False,1,18,NaN,NaN
4,0,0,7,0,0.3,18,0.00,0.00,0.00,2.16,...,1,-106785,39461,146246,60,False,0,18,NaN,NaN
5,0,0,4,0,1.5,18,0.01,0.01,0.00,0.32,...,0,-135179,170729,305908,60,True,1,18,NaN,NaN
6,0,0,10,0,4.0,18,0.03,0.03,0.00,0.65,...,2,-164493,60456,224949,60,True,0,18,NaN,NaN
7,0,0,-12,0,0.1,18,0.00,0.00,0.00,0.03,...,-3,-102072,43802,145874,60,False,0,18,NaN,NaN
8,0,0,0,0,0.0,18,0.00,0.00,0.00,0.00,...,0,-845094,1772,846866,60,True,0,18,NaN,NaN
9,0,0,19,0,2.7,18,0.24,0.24,0.00,0.53,...,2,-74076,55502,129578,60,False,0,18,NaN,NaN
10,0,0,18,0,22.3,18,0.26,0.26,0.00,1.28,...,2,-81301,20567,101868,60,False,0,18,NaN,NaN
11,0,1,32,1,2.8,18,0.02,0.02,0.00,0.33,...,7,3449,65139,61690,60,True,0,18,NaN,NaN
12,0,0,6,0,1.0,18,0.01,0.01,0.00,1.54,...,1,83815,112154,28339,60,False,0,18,NaN,NaN
13,0,3,41,1,1.5,18,0.01,0.70,0.69,0.22,...,15,-44337,43456,87793,60,True,0,18,NaN,NaN
14,0,1,21,0,3.6,18,0.01,1.20,1.19,0.16,...,9,262951,282622,19671,61,False,0,18,NaN,NaN
15,0,0,26,1,2.6,18,0.04,0.04,0.00,0.09,...,6,473284,494228,20944,62,True,0,18,NaN,NaN
16,0,0,7,0,1.1,18,0.01,0.01,0.00,1.59,...,2,83690,129115,45425,63,False,0,18,NaN,NaN
17,0,1,32,1,23.8,18,0.02,0.02,0.00,0.16,...,7,23599,103085,79486,63,True,0,18,NaN,NaN
18,0,0,14,0,3.3,18,0.08,0.08,0.00,0.29,...,2,1303,64265,62962,63,False,0,18,NaN,NaN
19,0,0,8,0,1.3,18,0.01,0.01,0.00,1.52,...,2,-50765,63683,114448,63,False,0,18,NaN,NaN
20,0,0,7,0,2.5,18,0.02,0.02,0.00,0.78,...,2,-111877,28918,140795,63,True,0,18,NaN,NaN
21,0,0,0,0,0.0,18,0.00,0.00,0.00,0.00,...,0,-122876,13099,135975,63,True,0,18,NaN,NaN
22,0,3,30,1,0.8,18,0.00,0.00,0.00,0.74,...,9,-635720,3669,639389,62,False,0,18,NaN,NaN
23,0,0,11,0,0.8,18,0.00,0.00,0.00,0.81,...,2,-69003,22156,91159,62,True,0,18,NaN,NaN
24,0,0,25,1,0.8,18,0.01,0.01,0.00,0.22,...,6,20704,58314,37610,62,False,0,18,NaN,NaN
25,0,0,9,0,4.4,18,0.02,0.02,0.00,1.07,...,2,56604,74515,17911,62,True,0,18,NaN,NaN
26,0,2,28,1,3.5,18,0.02,0.21,0.19,0.40,...,8,-31511,18175,49686,62,False,0,18,NaN,NaN
27,0,0,14,0,4.2,18,0.02,0.02,0.00,1.52,...,2,12219,40819,28600,62,False,0,18,NaN,NaN
28,0,3,27,1,1.8,18,0.01,0.01,0.00,0.36,...,9,41344,62703,21359,62,True,0,18,NaN,NaN
29,0,0,9,0,2.8,18,0.02,0.10,0.08,0.99,...,2,135054,181718,46664,62,True,0,18,NaN,NaN
30,0,0,16,0,1.8,18,0.03,0.03,0.00,1.09,...,2,629162,660086,30924,64,False,0,18,NaN,NaN
31,0,0,16,0,38.3,18,0.28,0.28,0.00,0.24,...,2,203680,247481,43801,65,True,0,18,NaN,NaN
32,0,0,26,1,4.4,18,0.04,0.04,0.00,0.17,...,6,388743,415473,26730,66,False,0,18,NaN,NaN
33,0,0,5,0,5.1,18,0.02,0.29,0.27,1.75,...,1,388743,415473,26730,66,True,0,18,NaN,NaN
34,0,0,10,0,0.5,18,0.00,0.00,0.00,0.97,...,1,-1568,46752,48320,66,True,0,18,NaN,NaN
35,0,0,6,0,1.2,18,0.01,0.01,0.00,2.56,...,1,-171341,14804,186145,65,False,0,18,NaN,NaN
36,0,0,10,0,1.5,18,0.00,0.00,0.00,1.46,...,1,-23626,27319,50945,65,True,0,18,NaN,NaN
37,0,0,0,0,0.0,18,0.00,0.00,0.00,0.00,...,0,-535888,26041,561929,64,False,0,18,NaN,NaN

### Current season cleaning

In [46]:
# Ensure the data is cleaned for merged_gw.csv for the current gwk
# Define the column index for 'minutes' (0-based index)
# Define the expected number of columns
EXPECTED_COLUMNS = 42  # Change this to the correct number of columns
MINUTES_COLUMN_INDEX = pd.read_csv(f"./data/vaastav/data/20{'24-25'}/gws/merged_gw.csv", on_bad_lines='skip').columns.tolist().index('minutes')
FEATURES_TO_REMOVE = 7  # Number of features to delete after 'minutes'

# Input and output file paths
data_file = './data/vaastav/data/2024-25/gws/merged_gw.csv'
output_file = "cleaned_file.csv"

with open(data_file, "r", newline="", encoding="utf-8") as infile, \
    open(output_file, "w", newline="", encoding="utf-8") as outfile:
    reader = csv.reader(infile)
    writer = csv.writer(outfile)

    # Read and write the header row
    header = next(reader)
    writer.writerow(header)

    for row in reader:
        # print(row)
        if len(row) > EXPECTED_COLUMNS:
            row = row[:MINUTES_COLUMN_INDEX + 1] + row[MINUTES_COLUMN_INDEX + FEATURES_TO_REMOVE + 1:]
        writer.writerow(row)

# Update the data file path
outfile = pd.read_csv(output_file)

# Save the cleaned file
output_file = './data/vaastav/data/20'+ '24-25' +'/gws/merged_gw.csv'
outfile.to_csv(output_file, index=False)
print(f"Cleaned file saved as {output_file}")

Cleaned file saved as ./data/vaastav/data/2024-25/gws/merged_gw.csv

In [24]:
merge_fpl_understat_data("./data/vaastav/data/2025-26/players/", "./data/vaastav/data/2025-26/understat/", "25-26")
add_difficulty('25-26')
add_xP('25-26', gw)
add_rolling_avgs('25-26')
owenership_change('25-26', gw)
odds('25-26', gw)
merge_files('25-26')

['./data/vaastav/data/2025-26/players/Aaron_Hickey_116', './data/vaastav/data/2025-26/players/Aaron_Ramsdale_674', './data/vaastav/data/2025-26/players/Aaron_Ramsey_211', './data/vaastav/data/2025-26/players/Aaron_Wan-Bissaka_610', './data/vaastav/data/2025-26/players/Aarón_Anselmino_234', './data/vaastav/data/2025-26/players/Abdallah_Sima_165', './data/vaastav/data/2025-26/players/Abdoullah_Ba_554', './data/vaastav/data/2025-26/players/Abdukodir_Khusanov_406', './data/vaastav/data/2025-26/players/Adama_Traoré Diarra_326', './data/vaastav/data/2025-26/players/Adam_Aznou_667', './data/vaastav/data/2025-26/players/Adam_Smith_73', './data/vaastav/data/2025-26/players/Adam_Webster_153', './data/vaastav/data/2025-26/players/Adam_Wharton_273', './data/vaastav/data/2025-26/players/Adrian_Mazilu_176', './data/vaastav/data/2025-26/players/Adrien_Truffert_74', './data/vaastav/data/2025-26/players/Ahmed_Abdullahi_562', './data/vaastav/data/2025-26/players/Aji_Alese_533', './data/vaastav/data/2025-26/players/Alan_Browne_555', './data/vaastav/data/2025-26/players/Albert_Sambi Lokonga_29', './data/vaastav/data/2025-26/players/Alejandro_Garnacho Ferreyra_453', './data/vaastav/data/2025-26/players/Alexander_Isak_499', './data/vaastav/data/2025-26/players/Alexis_Mac Allister_386', './data/vaastav/data/2025-26/players/Alex_Cairns_340', './data/vaastav/data/2025-26/players/Alex_Iwobi_324', './data/vaastav/data/2025-26/players/Alex_Murphy_481', './data/vaastav/data/2025-26/players/Alex_Paulsen_70', './data/vaastav/data/2025-26/players/Alex_Scott_90', './data/vaastav/data/2025-26/players/Alfie_Pond_641', './data/vaastav/data/2025-26/players/Alisson_Becker_366', './data/vaastav/data/2025-26/players/Alphonse_Areola_600', './data/vaastav/data/2025-26/players/Altay_Bayındır_431', './data/vaastav/data/2025-26/players/Amadou_Onana_59', './data/vaastav/data/2025-26/players/Amad_Diallo_452', './data/vaastav/data/2025-26/players/Amara_Nallo_378', './data/vaastav/data/2025-26/players/Amine_Adli_697', './data/vaastav/data/2025-26/players/Andreas_Hoelgebaum Pereira_327', './data/vaastav/data/2025-26/players/Andrew_Moran_177', './data/vaastav/data/2025-26/players/Andrew_Robertson_372', './data/vaastav/data/2025-26/players/Andrey_Nascimento dos Santos_246', './data/vaastav/data/2025-26/players/Andre_Harriman-Annous_711', './data/vaastav/data/2025-26/players/Andrés_García_42', './data/vaastav/data/2025-26/players/André_Onana_432', './data/vaastav/data/2025-26/players/André_Trindade da Costa Neto_643', './data/vaastav/data/2025-26/players/Andy_Irving_621', './data/vaastav/data/2025-26/players/Angus_Gunn_675', './data/vaastav/data/2025-26/players/Anthony_Elanga_486', './data/vaastav/data/2025-26/players/Anthony_Gordon_485', './data/vaastav/data/2025-26/players/Anthony_Patterson_528', './data/vaastav/data/2025-26/players/Antoine_Semenyo_82', './data/vaastav/data/2025-26/players/Antonee_Robinson_316', './data/vaastav/data/2025-26/players/Antoni_Milambo_122', './data/vaastav/data/2025-26/players/Antony_dos Santos_454', './data/vaastav/data/2025-26/players/Anton_Stach_660', './data/vaastav/data/2025-26/players/Antonín_Kinský_567', './data/vaastav/data/2025-26/players/Antoñito_Cordero Campillo_492', './data/vaastav/data/2025-26/players/Archie_Gray_591', './data/vaastav/data/2025-26/players/Armando_Broja_680', './data/vaastav/data/2025-26/players/Arnaud_Kalimuendo_696', './data/vaastav/data/2025-26/players/Arthur_Masuaku_678', './data/vaastav/data/2025-26/players/Asher_Agbinone_274', './data/vaastav/data/2025-26/players/Ashley_Barnes_218', './data/vaastav/data/2025-26/players/Ashley_Phillips_576', './data/vaastav/data/2025-26/players/Axel_Tuanzebe_198', './data/vaastav/data/2025-26/players/Ayden_Heaven_447', './data/vaastav/data/2025-26/players/Bafodé_Diakité_685', './data/vaastav/data/2025-26/players/Bart_Verbruggen_139', './data/vaastav/data/2025-26/players/Bashir_Humphreys_193', './data/vaastav/data/2025-26/players/Bastien_Meupiyou Menadjou_639', './data/vaastav/data/2025-26/players/Benjamin_Arthur_114', './data/vaastav/data/2025-26/players/Benjamin_Fredrick_115', './data/vaastav/data/2025-26/players/Benjamin_Lecomte_664', './data/vaastav/data/2025-26/players/Benjamin_Sesko_681', './data/vaastav/data/2025-26/players/Benjamin_White_11', './data/vaastav/data/2025-26/players/Benoît_Badiashile Mukinayi_229', './data/vaastav/data/2025-26/players/Ben_Broggio_60', './data/vaastav/data/2025-26/players/Ben_Davies_571', './data/vaastav/data/2025-26/players/Ben_Doak_391', './data/vaastav/data/2025-26/players/Ben_Gannon-Doak_391', './data/vaastav/data/2025-26/players/Ben_Winterburn_96', './data/vaastav/data/2025-26/players/Bernardo_Mota Veiga de Carvalho e Silva_416', './data/vaastav/data/2025-26/players/Bernd_Leno_314', './data/vaastav/data/2025-26/players/Bertrand_Traoré_735', './data/vaastav/data/2025-26/players/Blondy_Nna Noukeu_530', './data/vaastav/data/2025-26/players/Borna_Sosa_259', './data/vaastav/data/2025-26/players/Boubacar_Kamara_58', './data/vaastav/data/2025-26/players/Boubacar_Traoré_649', './data/vaastav/data/2025-26/players/Bradley_Burrowes_702', './data/vaastav/data/2025-26/players/Brajan_Gruda_162', './data/vaastav/data/2025-26/players/Brandon_Austin_566', './data/vaastav/data/2025-26/players/Brayden_Clarke_13', './data/vaastav/data/2025-26/players/Brenden_Aaronson_350', './data/vaastav/data/2025-26/players/Brennan_Johnson_580', './data/vaastav/data/2025-26/players/Brian_Brobbey_730', './data/vaastav/data/2025-26/players/Bruno_Borges Fernandes_449', './data/vaastav/data/2025-26/players/Bruno_Guimarães Rodriguez Moura_488', './data/vaastav/data/2025-26/players/Bryan_Gil Salvatierra_590', './data/vaastav/data/2025-26/players/Bryan_Mbeumo_119', './data/vaastav/data/2025-26/players/Bukayo_Saka_16', './data/vaastav/data/2025-26/players/Caleb_Kporha_265', './data/vaastav/data/2025-26/players/Callan_McKenna_69', './data/vaastav/data/2025-26/players/Callum_Bates_306', './data/vaastav/data/2025-26/players/Callum_Hudson-Odoi_516', './data/vaastav/data/2025-26/players/Callum_Marshall_626', './data/vaastav/data/2025-26/players/Callum_Olusesi_595', './data/vaastav/data/2025-26/players/Callum_Wilson_671', './data/vaastav/data/2025-26/players/Calvin_Bassey_318', './data/vaastav/data/2025-26/players/Calvin_Ramsay_380', './data/vaastav/data/2025-26/players/Caoimhín_Kelleher_101', './data/vaastav/data/2025-26/players/Carlos Henrique_Casimiro_457', './data/vaastav/data/2025-26/players/Carlos Miguel_dos Santos Pereira_503', './data/vaastav/data/2025-26/players/Carlos_Alcaraz Durán_301', './data/vaastav/data/2025-26/players/Carlos_Baleba_167', './data/vaastav/data/2025-26/players/Carl_Rushworth_141', './data/vaastav/data/2025-26/players/Chadi_Riad Dnanou_262', './data/vaastav/data/2025-26/players/Charalampos_Kostoulas_181', './data/vaastav/data/2025-26/players/Charlie_Crew_359', './data/vaastav/data/2025-26/players/Charlie_Tasker_156', './data/vaastav/data/2025-26/players/Cheick_Doucouré_268', './data/vaastav/data/2025-26/players/Chemsdine_Talbi_553', './data/vaastav/data/2025-26/players/Chido_Obi_467', './data/vaastav/data/2025-26/players/Christantus_Uche_732', './data/vaastav/data/2025-26/players/Christian_Nørgaard_24', './data/vaastav/data/2025-26/players/Christopher_Nkunku_240', './data/vaastav/data/2025-26/players/Chris_Mepham_79', './data/vaastav/data/2025-26/players/Chris_Richards_261', './data/vaastav/data/2025-26/players/Chris_Rigg_551', './data/vaastav/data/2025-26/players/Chris_Wood_525', './data/vaastav/data/2025-26/players/Claudio_Echeverri_425', './data/vaastav/data/2025-26/players/Coby_Ebere_307', './data/vaastav/data/2025-26/players/Cody_Gakpo_384', './data/vaastav/data/2025-26/players/Cole_Palmer_235', './data/vaastav/data/2025-26/players/Connor_Roberts_186', './data/vaastav/data/2025-26/players/Conor_Bradley_375', './data/vaastav/data/2025-26/players/Cristhian_Mosquera_662', './data/vaastav/data/2025-26/players/Cristian_Romero_569', './data/vaastav/data/2025-26/players/Crysencio_Summerville_615', './data/vaastav/data/2025-26/players/Curtis_Jones_388', './data/vaastav/data/2025-26/players/Daichi_Kamada_271', './data/vaastav/data/2025-26/players/Dane_Scarlett_599', './data/vaastav/data/2025-26/players/Dango_Ouattara_83', './data/vaastav/data/2025-26/players/Daniel_Adu-Adjei_99', './data/vaastav/data/2025-26/players/Daniel_Ballard_531', './data/vaastav/data/2025-26/players/Daniel_Bentley_629', './data/vaastav/data/2025-26/players/Daniel_James_353', './data/vaastav/data/2025-26/players/Daniel_Muñoz Mejía_256', './data/vaastav/data/2025-26/players/Danny_Welbeck_178', './data/vaastav/data/2025-26/players/Dan_Burn_476', './data/vaastav/data/2025-26/players/Dan_Ndoye_669', './data/vaastav/data/2025-26/players/Dan_Neil_549', './data/vaastav/data/2025-26/players/Darko_Churlinov_204', './data/vaastav/data/2025-26/players/Darko_Gyabi_361', './data/vaastav/data/2025-26/players/Darwin_Núñez Ribeiro_397', './data/vaastav/data/2025-26/players/David_Brooks_86', './data/vaastav/data/2025-26/players/David_Mota Veiga Teixeira do Carmo_509', './data/vaastav/data/2025-26/players/David_Møller Wolfe_682', './data/vaastav/data/2025-26/players/David_Ozoh_280', './data/vaastav/data/2025-26/players/David_Raya Martín_1', './data/vaastav/data/2025-26/players/Dean_Henderson_253', './data/vaastav/data/2025-26/players/Declan_Rice_21', './data/vaastav/data/2025-26/players/Dejan_Kulusevski_583', './data/vaastav/data/2025-26/players/Dennis_Cirkin_535', './data/vaastav/data/2025-26/players/Dermot_Mee_435', './data/vaastav/data/2025-26/players/Destiny_Udogie_574', './data/vaastav/data/2025-26/players/Diego_Coppola_144', './data/vaastav/data/2025-26/players/Diego_Gómez Amarilla_169', './data/vaastav/data/2025-26/players/Diego_León Blanco_439', './data/vaastav/data/2025-26/players/Dilane_Bakwa_734', './data/vaastav/data/2025-26/players/Diogo_Dalot Teixeira_440', './data/vaastav/data/2025-26/players/Divine_Mukasa_739', './data/vaastav/data/2025-26/players/Djed_Spence_573', './data/vaastav/data/2025-26/players/Dominic_Calvert-Lewin_691', './data/vaastav/data/2025-26/players/Dominic_Sadi_94', './data/vaastav/data/2025-26/players/Dominic_Solanke-Mitchell_596', './data/vaastav/data/2025-26/players/Dominik_Szoboszlai_387', './data/vaastav/data/2025-26/players/Donyell_Malen_53', './data/vaastav/data/2025-26/players/Douglas Luiz_Soares de Paulo_699', './data/vaastav/data/2025-26/players/Dwight_McNeil_300', './data/vaastav/data/2025-26/players/Dário_Luís Essugo_247', './data/vaastav/data/2025-26/players/Eberechi_Eze_266', './data/vaastav/data/2025-26/players/Eddie_Nketiah_284', './data/vaastav/data/2025-26/players/Ederson_Santana de Moraes_399', './data/vaastav/data/2025-26/players/Edson_Álvarez Velázquez_616', './data/vaastav/data/2025-26/players/Eiran_Cashin_154', './data/vaastav/data/2025-26/players/El Hadji Malick_Diouf_603', './data/vaastav/data/2025-26/players/Eli Junior_Kroupi_100', './data/vaastav/data/2025-26/players/Eliezer_Mayenda Dossou_561', './data/vaastav/data/2025-26/players/Elijah_Campbell_705', './data/vaastav/data/2025-26/players/Ellery_Balcombe_102', './data/vaastav/data/2025-26/players/Elliot_Anderson_517', './data/vaastav/data/2025-26/players/Elyh_Harrison_433', './data/vaastav/data/2025-26/players/Emerson_Palmieri dos Santos_604', './data/vaastav/data/2025-26/players/Emile_Smith Rowe_325', './data/vaastav/data/2025-26/players/Emiliano_Buendía Stati_50', './data/vaastav/data/2025-26/players/Emiliano_Martínez Romero_32', './data/vaastav/data/2025-26/players/Emil_Krafth_479', './data/vaastav/data/2025-26/players/Emmanuel_Agbadou_631', './data/vaastav/data/2025-26/players/Endo_Wataru_392', './data/vaastav/data/2025-26/players/Enes_Ünal_98', './data/vaastav/data/2025-26/players/Enock_Agyei_203', './data/vaastav/data/2025-26/players/Enso_González Medina_652', './data/vaastav/data/2025-26/players/Enzo_Barrenechea_56', './data/vaastav/data/2025-26/players/Enzo_Fernández_237', './data/vaastav/data/2025-26/players/Enzo_Le Fée_547', './data/vaastav/data/2025-26/players/Eric_da Silva Moreira_523', './data/vaastav/data/2025-26/players/Erling_Haaland_430', './data/vaastav/data/2025-26/players/Estêvão_Almeida de Oliveira Gonçalves_238', './data/vaastav/data/2025-26/players/Ethan_Ampadu_354', './data/vaastav/data/2025-26/players/Ethan_Nwaneri_25', './data/vaastav/data/2025-26/players/Ethan_Pinnock_111', './data/vaastav/data/2025-26/players/Ethan_Wheatley_468', './data/vaastav/data/2025-26/players/Etienne_Green_184', './data/vaastav/data/2025-26/players/Evann_Guessand_677', './data/vaastav/data/2025-26/players/Evan_Ferguson_179', './data/vaastav/data/2025-26/players/Ezri_Konsa Ngoyo_38', './data/vaastav/data/2025-26/players/Fabian_Schär_474', './data/vaastav/data/2025-26/players/Facundo_Buonanotte_168', './data/vaastav/data/2025-26/players/Federico_Chiesa_385', './data/vaastav/data/2025-26/players/Felipe_Rodrigues da Silva_511', './data/vaastav/data/2025-26/players/Ferdi_Kadıoğlu_148', './data/vaastav/data/2025-26/players/Fer_López González_645', './data/vaastav/data/2025-26/players/Filip_Jörgensen_221', './data/vaastav/data/2025-26/players/Filip_Marschall_35', './data/vaastav/data/2025-26/players/Florentino Ibrain_Morris Luís_722', './data/vaastav/data/2025-26/players/Florian_Wirtz_382', './data/vaastav/data/2025-26/players/Francisco Evanilson_de Lima Barbosa_97', './data/vaastav/data/2025-26/players/Franco_Umeh-Chibueze_282', './data/vaastav/data/2025-26/players/Frank_Onyeka_128', './data/vaastav/data/2025-26/players/Freddie_Potts_623', './data/vaastav/data/2025-26/players/Freddie_Woodman_369', './data/vaastav/data/2025-26/players/Fábio_Ferreira Vieira_23', './data/vaastav/data/2025-26/players/Fábio_Freitas Gouveia Carvalho_123', './data/vaastav/data/2025-26/players/Fábio_Soares Silva_655', './data/vaastav/data/2025-26/players/Gabriel_dos Santos Magalhães_5', './data/vaastav/data/2025-26/players/Gabriel_Fernando de Jesus_31', './data/vaastav/data/2025-26/players/Gabriel_Gudmundsson_347', './data/vaastav/data/2025-26/players/Gabriel_Martinelli Silva_19', './data/vaastav/data/2025-26/players/Gabriel_Słonina_223', './data/vaastav/data/2025-26/players/Garang_Kuol_496', './data/vaastav/data/2025-26/players/George_Earthy_620', './data/vaastav/data/2025-26/players/Georginio_Rutter_158', './data/vaastav/data/2025-26/players/Gianluigi_Donnarumma_736', './data/vaastav/data/2025-26/players/Giorgi_Mamardashvili_367', './data/vaastav/data/2025-26/players/Giovanni_Leoni_692', './data/vaastav/data/2025-26/players/Gonçalo Manuel_Ganchinho Guedes_647', './data/vaastav/data/2025-26/players/Granit_Xhaka_668', './data/vaastav/data/2025-26/players/Guglielmo_Vicario_565', './data/vaastav/data/2025-26/players/Guido_Rodríguez_618', './data/vaastav/data/2025-26/players/Gustavo_Nunes Fernandes Gomes_127', './data/vaastav/data/2025-26/players/Habib_Diarra_544', './data/vaastav/data/2025-26/players/Hamed_Traorè_93', './data/vaastav/data/2025-26/players/Hannes_Delcroix_188', './data/vaastav/data/2025-26/players/Hannibal_Mejbri_207', './data/vaastav/data/2025-26/players/Harrison_Armstrong_305', './data/vaastav/data/2025-26/players/Harrison_Ashby_482', './data/vaastav/data/2025-26/players/Harrison_Jones_557', './data/vaastav/data/2025-26/players/Harrison_Reed_336', './data/vaastav/data/2025-26/players/Harry_Amass_445', './data/vaastav/data/2025-26/players/Harry_Gray_741', './data/vaastav/data/2025-26/players/Harry_Maguire_442', './data/vaastav/data/2025-26/players/Harry_Tyrer_289', './data/vaastav/data/2025-26/players/Harry_Wilson_329', './data/vaastav/data/2025-26/players/Harvey_Barnes_487', './data/vaastav/data/2025-26/players/Harvey_Elliott_389', './data/vaastav/data/2025-26/players/Hjalmar_Ekdal_190', './data/vaastav/data/2025-26/players/Hugo_Bueno López_633', './data/vaastav/data/2025-26/players/Hugo_Ekitiké_661', './data/vaastav/data/2025-26/players/Hwang_Hee-chan_642', './data/vaastav/data/2025-26/players/Hákon Rafn_Valdimarsson_105', './data/vaastav/data/2025-26/players/Ian_Maatsen_39', './data/vaastav/data/2025-26/players/Ian_Poveda-Ocampo_550', './data/vaastav/data/2025-26/players/Ibrahima_Konaté_374', './data/vaastav/data/2025-26/players/Ibrahim_Sangaré_521', './data/vaastav/data/2025-26/players/Idrissa Gana_Gueye_302', './data/vaastav/data/2025-26/players/Igor Jesus_Maciel da Cruz_526', './data/vaastav/data/2025-26/players/Igor Julio_dos Santos de Paulo_149', './data/vaastav/data/2025-26/players/Igor Thiago_Nascimento Rodrigues_136', './data/vaastav/data/2025-26/players/Ilia_Gruev_356', './data/vaastav/data/2025-26/players/Iliman_Ndiaye_299', './data/vaastav/data/2025-26/players/Illan_Meslier_339', './data/vaastav/data/2025-26/players/Illia_Zabarnyi_71', './data/vaastav/data/2025-26/players/Isaac_Hayden_495', './data/vaastav/data/2025-26/players/Isaac_Heath_308', './data/vaastav/data/2025-26/players/Isaac_Schmidt_349', './data/vaastav/data/2025-26/players/Ismaïla_Sarr_267', './data/vaastav/data/2025-26/players/Ismeal_Kabia_28', './data/vaastav/data/2025-26/players/Issa_Diop_320', './data/vaastav/data/2025-26/players/Iwan_Morgan_137', './data/vaastav/data/2025-26/players/Jackson_Tchatchoua_695', './data/vaastav/data/2025-26/players/Jack_Fletcher_462', './data/vaastav/data/2025-26/players/Jack_Grealish_419', './data/vaastav/data/2025-26/players/Jack_Harrison_352', './data/vaastav/data/2025-26/players/Jack_Hinshelwood_163', './data/vaastav/data/2025-26/players/Jack_Moorhouse_464', './data/vaastav/data/2025-26/players/Jacob_Bruun Larsen_202', './data/vaastav/data/2025-26/players/Jacob_Murphy_489', './data/vaastav/data/2025-26/players/Jacob_Ramsey_52', './data/vaastav/data/2025-26/players/Jacob_Slater_155', './data/vaastav/data/2025-26/players/Jadon_Sancho_456', './data/vaastav/data/2025-26/players/Jaidon_Anthony_200', './data/vaastav/data/2025-26/players/Jair_Paula da Cunha Filho_510', './data/vaastav/data/2025-26/players/Jaka_Bijol_344', "./data/vaastav/data/2025-26/players/Jake_O'Brien_293", './data/vaastav/data/2025-26/players/Jakub_Kiwior_9', './data/vaastav/data/2025-26/players/Jamaal_Lascelles_480', './data/vaastav/data/2025-26/players/Jamaldeen_Jimoh-Aloba_62', './data/vaastav/data/2025-26/players/James_Garner_303', './data/vaastav/data/2025-26/players/James_Hill_77', './data/vaastav/data/2025-26/players/James_Justin_706', './data/vaastav/data/2025-26/players/James_Maddison_581', './data/vaastav/data/2025-26/players/James_McAtee_426', './data/vaastav/data/2025-26/players/James_McConnell_394', './data/vaastav/data/2025-26/players/James_Milner_170', './data/vaastav/data/2025-26/players/James_Tarkowski_291', './data/vaastav/data/2025-26/players/James_Trafford_182', './data/vaastav/data/2025-26/players/James_Ward-Prowse_614', './data/vaastav/data/2025-26/players/James_Wright_688', './data/vaastav/data/2025-26/players/Jamie_Bynoe-Gittens_239', './data/vaastav/data/2025-26/players/Jan Paul_van Hecke_151', './data/vaastav/data/2025-26/players/Jarrad_Branthwaite_290', './data/vaastav/data/2025-26/players/Jarrod_Bowen_624', './data/vaastav/data/2025-26/players/Jason_Steele_138', './data/vaastav/data/2025-26/players/Jayce_Fitzgerald_461', './data/vaastav/data/2025-26/players/Jaydee_Canvot_723', './data/vaastav/data/2025-26/players/Jayden_Bogle_342', './data/vaastav/data/2025-26/players/Jayden_Danns_398', './data/vaastav/data/2025-26/players/Jayden_Meghoma_118', './data/vaastav/data/2025-26/players/Jaydon_Banel_213', './data/vaastav/data/2025-26/players/Jay_Matete_558', './data/vaastav/data/2025-26/players/Jean-Clair_Todibo_609', './data/vaastav/data/2025-26/players/Jean-Philippe_Mateta_283', './data/vaastav/data/2025-26/players/Jean-Ricner_Bellegarde_644', './data/vaastav/data/2025-26/players/Jefferson_Lerma Solís_272', './data/vaastav/data/2025-26/players/Jenson_Metcalfe_309', './data/vaastav/data/2025-26/players/Jenson_Seelt_542', './data/vaastav/data/2025-26/players/Jeremie_Frimpong_370', './data/vaastav/data/2025-26/players/Jeremy_Sarmiento Morante_171', './data/vaastav/data/2025-26/players/Jesurun_Rak-Sakyi_