In [1]:
# %pip install pycaret

In [2]:
import pandas as pd
from pycaret.regression import *

In [23]:
gw=28
data_22_23 = pd.read_csv('./data/joint/22-23/merged_player_data.csv',).dropna()
data_23_24 = pd.read_csv('./data/joint/23-24/merged_player_data.csv').dropna()
data_24_25 = pd.read_csv('./data/joint/24-25/merged_player_data.csv')
data_tar = data_24_25[data_24_25['event']==gw]
data_24_25_ = data_24_25[data_24_25['event'] != gw]

data_24_25_ = data_24_25[data_24_25['event'] != 28]

data = pd.concat([data_22_23, data_23_24, data_24_25_])

In [ ]:

mid_data= data[(g_data['minutes_5'] >= 300) & (data['position'] == 'MID')]
mid_data_tar = data_tar[(g_data_tar['minutes_5'] >= 300) & (data_tar['position'] == '3')]

mid_xg_data = mid_data[g_features]
mid_xg_data_tar = mid_data_tar[g_features]

mid_data.reset_index(drop=True, inplace=True)
mid_xg_data.reset_index(drop=True, inplace=True)

mid_xg_data.drop(columns=['position'], inplace=True)
mid_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)

mid_xg_data

In [80]:
data_tar[data_tar['minutes_5'] < 200][['percenatge_net_transfers', 'ownership_change']]

      percenatge_net_transfers  ownership_change
43                   -0.718310           -4224.0
53                   -1.000000             -89.0
74                   -0.193548            -271.0
97                   -1.000000           -2079.0
126                  -0.571678          -13721.0
...                        ...               ...
8718                  0.245072           14316.0
8748                 -0.654102            -552.0
8765                 -0.681275            -353.0
8805                 -0.189241            -117.0
8834                  0.454586          115868.0

[283 rows x 2 columns]

In [81]:
data_tar[['minutes_5','percenatge_net_transfers', 'ownership_change']]

      minutes_5  percenatge_net_transfers  ownership_change
43         72.2                 -0.718310           -4224.0
53          0.0                 -1.000000             -89.0
74         78.0                 -0.193548            -271.0
97         53.2                 -1.000000           -2079.0
126        81.6                 -0.571678          -13721.0
...         ...                       ...               ...
8748       78.2                 -0.654102            -552.0
8765       30.2                 -0.681275            -353.0
8769        NaN                 -0.718805           -3175.0
8805       90.0                 -0.189241            -117.0
8834       90.0                  0.454586          115868.0

[341 rows x 3 columns]

In [ ]:
features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'ownership_change',

            'clean_sheets', 'expected_assists', 'expected_goal_involvements', 'expected_goals', 'expected_goals_conceded', 'goals_conceded', 'goals_scored', 'ict_index',
            'influence', 'creativity', 'threat', 'minutes', 'own_goals', 'penalties_missed', 'penalties_saved', 'red_cards', 'yellow_cards', 'saves', 'starts',
            'team_a_score', 'team_h_score', 'total_points', 'goals', 'shots', 'xG', 'xA', 'assists_x', 'assists_y', 'key_passes', 'npg', 'npxG', 'xGChain',  'xGBuildup',  'xP',

            'clean_sheets_1', 'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_missed_1', 'penalties_saved_1', 'red_cards_1', 'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1', 'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1',
            'xGBuildup_1',  'xP_1',

            'clean_sheets_2', 'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'goals_scored_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_missed_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2', 'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2',
            'xGBuildup_2',  'xP_2',

            'clean_sheets_3', 'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'goals_scored_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_missed_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3', 'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3',
            'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'goals_scored_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_missed_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4', 'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4',
            'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'goals_scored_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_missed_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5', 'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5',
            'xGBuildup_5',  'xP_5'
                        ]

g_features = [ 'position',  'xG', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',
              'red_cards', 'yellow_cards', 'starts', 'total_points', 'goals', 'shots',

            'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1',  'goals_scored_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2',  'goals_scored_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3',  'goals_scored_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4',  'goals_scored_4', 'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5',  'goals_scored_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

# for i in range(1, 6):
#     for feature in features:
#         features.append(f'{feature}_{i}')
len(g_features)

154

# Goals

## Def

In [25]:

def_data= data[(g_data['minutes_5'] >= 300) & (data['position'] == 'DEF')]
def_data_tar = data_tar[(g_data_tar['minutes_5'] >= 300) & (data_tar['position'] == '2')]

def_xg_data = def_data[g_features]
def_xg_data_tar = def_data_tar[g_features]

def_data.reset_index(drop=True, inplace=True)
def_xg_data.reset_index(drop=True, inplace=True)

In [26]:
def_xg_data.drop(columns=['position'], inplace=True)
def_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)

In [27]:
def_xg_data

,xG,whh,whd,wha,was_home,team_h_difficulty,team_a_difficulty,ownership_change,ict_index,influence,...,xG_5,xA_5,assists_x_5,assists_y_5,key_passes_5,npg_5,npxG_5,xGChain_5,xGBuildup_5,xP_5
0,0.000000,0.354,0.281,0.365,True,3.0,3.0,NaN,3.8,27.2,...,0.35,0.41,NaN,0.0,2.0,1.0,0.35,0.51,0.47,10.5
1,0.000000,0.595,0.230,0.175,False,3.0,3.0,NaN,2.1,18.8,...,0.35,0.48,NaN,0.0,3.0,1.0,0.35,0.70,0.66,15.0
2,0.014138,0.316,0.271,0.413,True,3.0,3.0,NaN,2.9,12.8,...,0.10,0.48,NaN,0.0,3.0,1.0,0.10,0.61,0.58,17.7
3,0.047519,0.308,0.290,0.402,False,3.0,2.0,NaN,1.1,5.2,...,0.06,0.79,NaN,0.0,3.0,1.0,0.06,0.76,0.38,18.9
4,0.000000,0.174,0.228,0.598,True,4.0,3.0,NaN,1.8,16.6,...,0.11,0.79,NaN,0.0,3.0,1.0,0.11,1.60,1.23,17.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,0.143915,0.464,0.264,0.272,True,2.0,3.0,NaN,2.8,14.2,...,0.15,0.00,NaN,0.0,0.0,0.0,0.15,1.11,1.09,14.4
319,0.031046,0.460,0.278,0.262,False,3.0,3.0,NaN,4.6,34.8,...,0.30,0.00,NaN,0.0,0.0,0.0,0.30,1.18,1.01,14.4
320,0.176578,0.509,0.286,0.205,True,2.0,3.0,NaN,4.2,16.0,...,0.29,0.00,NaN,0.0,0.0,0.0,0.29,1.19,1.01,15.9
321,0.176578,0.509,0.286,0.205,True,2.0,3.0,NaN,4.2,16.0,...,0.29,0.00,NaN,0.0,0.0,0.0,0.29,1.19,1.01,15.9
322,0.023201,0.376,0.289,0.335,True,3.0,3.0,NaN,2.1,17.2,...,0.96,0.27,NaN,0.0,1.0,0.0,0.96,0.43,0.21,NaN

In [28]:
def_xg_model = setup(def_xg_data, target = 'xG')

In [30]:
def_xg_best = def_xg_model.compare_models()

In [31]:
def_xg_best

ElasticNet(random_state=2625)

In [32]:
def_xg_model.evaluate_model(def_xg_best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [43]:
preds = def_xg_model.predict_model(def_xg_best, data=def_xg_data_tar)

preds.rename(columns={'prediction_label': 'xG_pred'}, inplace=True)

def_xg_preds = preds[['xG_pred']]
def_xg_preds

def_data_tar = pd.concat([def_data_tar, def_xg_preds], axis=1)
def_data_tar

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,selected_3,selected_5,xG_pred
1267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.649,0.208,0.144,1291115.0,2151439.0,0.064594
1325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.649,0.208,0.144,58581.0,84556.0,0.064614
1445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.649,0.208,0.144,2942169.0,4665245.0,0.064605
1634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.649,0.208,0.144,631617.0,1062147.0,0.064447
1662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.649,0.208,0.144,2916848.0,4358089.0,0.064500
3257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.863,0.087,0.050,11174972.0,18516502.0,0.064469
3510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.863,0.087,0.050,2554921.0,3958152.0,0.064550
3642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.863,0.087,0.050,991145.0,1975561.0,0.064422
3738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.863,0.087,0.050,7710201.0,12824391.0,0.064602
4666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.288,0.250,0.463,2258708.0,4015348.0,0.064599
4744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.288,0.250,0.463,7710104.0,13749981.0,0.064443
4888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.288,0.250,0.463,573560.0,991822.0,0.064538
4963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.288,0.250,0.463,508925.0,880821.0,0.064618
5339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.400,0.254,0.346,1241330.0,2716308.0,0.064641
8058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.649,0.208,0.144,274804.0,394484.0,0.064608

## Mid

In [ ]:

mid_data= data[(g_data['minutes_5'] >= 300) & (data['position'] == 'MID')]
mid_data_tar = data_tar[(g_data_tar['minutes_5'] >= 300) & (data_tar['position'] == '3')]

mid_xg_data = mid_data[g_features]
mid_xg_data_tar = mid_data_tar[g_features]

mid_data.reset_index(drop=True, inplace=True)
mid_xg_data.reset_index(drop=True, inplace=True)

mid_xg_data.drop(columns=['position'], inplace=True)
mid_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)

mid_xg_data

In [68]:
mid_xg_data.drop(columns=['position'], inplace=True)
mid_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)

mid_xg_data

,xG,whh,whd,wha,was_home,team_h_difficulty,team_a_difficulty,percenatge_net_transfers,ict_index,influence,...,xG_5,xA_5,assists_x_5,assists_y_5,key_passes_5,npg_5,npxG_5,xGChain_5,xGBuildup_5,xP_5
0,0.057156,0.404,0.275,0.321,False,2.0,2.0,NaN,6.7,35.0,...,0.45,0.01,NaN,0.0,1.0,0.0,0.45,0.57,0.12,2.8
1,0.000000,0.100,0.189,0.711,True,4.0,2.0,NaN,1.9,7.2,...,0.63,1.03,NaN,0.0,5.0,0.0,0.63,0.97,0.15,8.2
2,0.000000,0.100,0.189,0.711,True,4.0,2.0,NaN,1.9,7.2,...,0.63,1.03,NaN,0.0,5.0,0.0,0.63,0.97,0.15,8.2
3,0.729754,0.332,0.266,0.402,True,3.0,3.0,NaN,6.6,11.2,...,1.60,0.76,NaN,0.0,8.0,1.0,1.60,2.77,1.21,13.7
4,0.172849,0.349,0.282,0.369,False,3.0,3.0,NaN,5.4,12.2,...,2.33,0.80,NaN,0.0,10.0,1.0,2.33,3.50,1.21,17.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,0.000000,0.464,0.264,0.272,True,2.0,3.0,NaN,1.1,5.8,...,0.62,1.97,NaN,1.0,8.0,0.0,0.62,3.92,1.76,21.2
307,0.440905,0.460,0.278,0.262,False,3.0,3.0,NaN,2.0,6.0,...,0.59,1.97,NaN,1.0,8.0,0.0,0.59,3.79,1.67,18.9
308,0.524366,0.509,0.286,0.205,True,2.0,3.0,NaN,4.2,10.0,...,0.52,1.29,NaN,1.0,4.0,0.0,0.52,3.15,1.78,16.4
309,0.524366,0.509,0.286,0.205,True,2.0,3.0,NaN,4.2,10.0,...,0.52,1.29,NaN,1.0,4.0,0.0,0.52,3.15,1.78,16.4
310,1.995942,0.376,0.289,0.335,True,3.0,3.0,NaN,19.9,74.0,...,0.97,0.03,NaN,0.0,1.0,0.0,0.97,2.48,1.48,NaN

In [54]:
mid_xg_model = setup(mid_xg_data, target = 'xG')

In [55]:
mid_xg_best = mid_xg_model.compare_models()

In [56]:
mid_xg_best

ElasticNet(random_state=4278)

In [ ]:
preds = mid_xg_model.predict_model(mid_xg_best, data=mid_xg_data_tar)

preds.rename(columns={'prediction_label': 'xG_pred'}, inplace=True)

mid_xg_preds = preds[['xG_pred']]
mid_xg_preds

mid_data_tar = pd.concat([mid_data_tar, mid_xg_preds], axis=1)
mid_data_tar

KeyError: "None of [Index(['xG_pred'], dtype='object')] are in the [columns]"

In [58]:
mid_data_tar['xG_pred']

       xG_pred   xG_pred
1293  0.214017  0.177326
1371  0.228117  0.196526
1500  0.208957  0.181041
1557  0.212992  0.178486
3451  0.204888  0.179121
3540  0.224513  0.190935
3571  0.221525  0.229661
3601  0.203721  0.190499
3671  0.225114  0.212789
4638  0.215112  0.185546
4715  0.221386  0.192123
4818  0.227451  0.205608
4992  0.202059  0.179007
5800  0.212802  0.182886
6695  0.222546  0.195696
7003  0.209176  0.194810
7260  0.237246  0.206310