In [2]:
%pip install pycaret

:

In [1]:
import pandas as pd
from pycaret.regression import *

In [2]:
gw=28
data_22_23 = pd.read_csv('./data/joint/22-23/merged_player_data.csv',).dropna()
data_23_24 = pd.read_csv('./data/joint/23-24/merged_player_data.csv').dropna()
data_24_25 = pd.read_csv('./data/joint/24-25/merged_player_data.csv')
data_tar = data_24_25[data_24_25['event']==gw]
data_24_25_ = data_24_25[data_24_25['event'] != gw]

data_24_25_ = data_24_25[data_24_25['event'] != 28]

data = pd.concat([data_22_23, data_23_24, data_24_25_])

In [3]:

xg_data= data[(data['minutes_5'] >= 300) & (data['position'] != 'GK')][['position', 'minutes_3', 'minutes_5', 'team_h_difficulty', 'team_a_difficulty', 'ict_index_3',  'ict_index_5',
                                                                     'influence_3', 'influence_5', 'creativity_3', 'creativity_5', 'threat_3', 'threat_5', 'was_home', 'xG', 'xG_3',
                                                                     'xG_5', 'expected_goals_3', 'expected_goals_5', 'goals_scored_3','goals_scored_5', 'whh', 'whd', 'wha']]

xg_data_tar = data_tar[(data_tar['minutes_5'] >= 300) & (data_tar['position'] != 'GK')][['position', 'minutes_3', 'minutes_5', 'team_h_difficulty', 'team_a_difficulty', 'ict_index_3',
                                                                                        'ict_index_5', 'influence_3', 'influence_5', 'creativity_3', 'creativity_5', 'threat_3',
                                                                                        'threat_5', 'was_home', 'xG_3', 'xG_5', 'expected_goals_3', 'expected_goals_5',
                                                                                        'goals_scored_3','goals_scored_5', 'whh', 'whd', 'wha']]

xg_data.reset_index(drop=True, inplace=True)

In [4]:

xg_model = setup(xg_data, target = 'xG')

In [5]:
xg_best = xg_model.compare_models()

Initiated  . . . . . . . . . . . . . . . . . .           21:20:39
Status     . . . . . . . . . . . . . . . . . .  Loading Estimator
Estimator  . . . . . . . . . . . . . . . . . .  Linear Regression

In [6]:
xg_best

BayesianRidge()

In [ ]:
xg_model.evaluate_model(xg_best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [8]:
preds = xg_model.predict_model(xg_best, data=xg_data_tar)
preds

,position,minutes_3,minutes_5,team_h_difficulty,team_a_difficulty,ict_index_3,ict_index_5,influence_3,influence_5,creativity_3,...,xG_3,xG_5,expected_goals_3,expected_goals_5,goals_scored_3,goals_scored_5,whh,whd,wha,prediction_label
126,3,235.0,408.0,3.0,3.0,19.500000,35.599998,60.400002,105.800003,39.000000,...,1.22,1.65,0.78,1.28,1.0,2.0,0.400,0.254,0.346,0.345466
181,4,270.0,450.0,3.0,3.0,23.600000,31.500000,83.599998,97.800003,9.400000,...,1.78,2.62,1.95,2.90,2.0,2.0,0.400,0.254,0.346,0.409215
249,3,257.0,347.0,3.0,3.0,10.700000,13.500000,36.400002,45.400002,30.000000,...,1.15,1.21,1.18,1.25,0.0,0.0,0.470,0.261,0.269,0.182383
429,4,178.0,313.0,3.0,3.0,17.400000,25.100000,84.599998,92.199997,32.099998,...,1.19,1.43,1.69,1.94,2.0,2.0,0.470,0.261,0.269,0.301031
450,3,264.0,347.0,4.0,3.0,16.500000,22.100000,32.799999,67.800003,111.199997,...,0.15,0.60,0.13,0.27,0.0,1.0,0.224,0.268,0.508,0.121035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8664,3,251.0,431.0,3.0,3.0,23.299999,44.400002,79.400002,154.199997,118.900002,...,0.26,0.37,0.25,0.41,0.0,0.0,0.400,0.254,0.346,0.158418
8715,1,270.0,360.0,3.0,3.0,9.700000,12.600000,87.000000,116.199997,10.000000,...,0.00,0.00,0.00,0.00,0.0,0.0,0.400,0.254,0.346,0.074023
8745,3,236.0,391.0,3.0,3.0,3.900000,9.200000,21.600000,45.599998,8.100000,...,0.08,0.08,0.08,0.08,0.0,0.0,0.400,0.254,0.346,0.112712
8801,3,270.0,450.0,3.0,3.0,17.799999,23.799999,46.000000,78.000000,91.599998,...,0.10,0.16,0.16,0.22,0.0,0.0,0.400,0.254,0.346,0.169316
8830,3,270.0,450.0,3.0,3.0,25.500000,41.799999,76.000000,125.800003,79.199997,...,1.32,3.06,0.92,2.27,1.0,2.0,0.400,0.254,0.346,0.349181

In [15]:
xg_data['selected_5']

KeyError: 'selected_5'