In [36]:
!pip install selenium

Collecting selenium
  Downloading selenium-4.39.0-py3-none-any.whl.metadata (7.5 kB)
Collecting urllib3<3.0,>=2.5.0 (from urllib3[socks]<3.0,>=2.5.0->selenium)
  Using cached urllib3-2.6.2-py3-none-any.whl.metadata (6.6 kB)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.32.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: certifi>=2025.10.5 in /home/ilyandho/.local/share/mamba/envs/pycaret/lib/python3.10/site-packages (from selenium) (2025.11.12)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /home/ilyandho/.local/share/mamba/envs/pycaret/lib/python3.10/site-packages (from selenium) (4.15.0)
Collecting websocket-client<2.0,>=1.8.0 (from selenium)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: attrs>=23.2.0 in /home/ilyandho/.local/share/mamba/envs/pycaret/lib/python3.10/site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in /home/ilyandho/.local/share/mamba/envs/pycaret/lib/python3.10/site-packages (from trio<1.0,>=0.31.0->selenium) (2.10)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: exceptiongroup in /home/ilyandho/.local/share/mamba/envs/pycaret/lib/python3.10/site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /home/ilyandho/.local/share/mamba/envs/pycaret/lib/python3.10/site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)
Collecting h11<1,>=0.16.0 (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Downloading selenium-4.39.0-py3-none-any.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 165.4 kB/s  0:01:06 eta 0:00:04
Downloading trio-0.32.0-py3-none-any.whl (512 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Using cached urllib3-2.6.2-py3-none-any.whl (131 kB)
Downloading websocket_client-1.9.0-py3-none-any.whl (82 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, websocket-client, urllib3, sniffio, outcome, h11, wsproto, trio, trio-websocket, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.5
    Uninstalling urllib3-1.26.5:
      Successfully uninstalled urllib3-1.26.5
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [selenium]/10 [selenium]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pycaret 3.3.2 requires matplotlib<3.8.0, but you have matplotlib 3.10.8 which is incompatible.
understatapi 0.7.0 requires urllib3==1.26.5, but you have urllib3 2.6.2 which is incompatible.
Successfully installed h11-0.16.0 outcome-1.3.0.post0 selenium-4.39.0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.32.0 trio-websocket-0.12.2 urllib3-2.6.2 websocket-client-1.9.0 wsproto-1.3.2

In [119]:
from understatapi import UnderstatClient
import pandas as pd
import requests

from thefuzz import process, fuzz

import requests
import pandas as pd
import json
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import os
import io

gw = 21

In [66]:
players_raw = pd.read_csv('https://raw.githubusercontent.com/ilyandho/FPL-Optimal-Transfer/refs/heads/FantasyGo/FPL%20predictors/with%20new%20features/data/vaastav/data/2025-26/players_raw.csv')
players_1 = pd.read_csv('https://raw.githubusercontent.com/ilyandho/FPL-Optimal-Transfer/refs/heads/FantasyGo/FPL%20predictors/with%20new%20features/data/vaastav/data/2025-26/gws/gw1.csv')
v = pd.read_csv('https://github.com/ilyandho/FPL-Optimal-Transfer/raw/refs/heads/FantasyGo/FPL%20predictors/with%20new%20features/data/vaastav/data/2025-26/players/Aaron_Hickey_116/gw.csv')
master_fpl_understat_map = pd.read_csv('https://raw.githubusercontent.com/ChrisMusson/FPL-ID-Map/main/Master.csv')

# player_gw_stats = pd.read_csv('https://github.com/olbauday/FPL-Core-Insights/raw/refs/heads/main/data/2025-2026/By%20Tournament/Premier%20League/GW1/player_gameweek_stats.csv')
# playerstats_1 = pd.read_csv('https://github.com/olbauday/FPL-Core-Insights/raw/refs/heads/main/data/2025-2026/By%20Tournament/Premier%20League/GW1/playerstats.csv')
players = pd.read_csv('https://github.com/olbauday/FPL-Core-Insights/raw/refs/heads/main/data/2025-2026/By%20Tournament/Premier%20League/GW1/players.csv')
teams = pd.read_csv('https://github.com/olbauday/FPL-Core-Insights/raw/refs/heads/main/data/2025-2026/By%20Tournament/Premier%20League/GW1/teams.csv')

git_data_olbauday_base = "https://github.com/olbauday/FPL-Core-Insights/raw/refs/heads/main/data/2025-2026/By%20Tournament/Premier%20League/"

fpl_fixtures_url = 'https://fantasy.premierleague.com/api/fixtures/?event='

player_summary = 'https://fantasy.premierleague.com/api/element-summary/'

# bootstrap = requests.get('https://fantasy.premierleague.com/api/bootstrap-static/').json()
# bootstrap

## Understat

In [ ]:
# Initialize the client
with UnderstatClient() as understat:
    # Use .league() to specify the league, then .get_player_data() for the season
    data = understat.league(league="EPL").get_player_data(season="2025")

# This will return a list of dictionaries containing player stats
understat_data = pd.DataFrame(data)
understat_data.to_csv(f'./data/understat/understat_data_{gw}.csv')
understat_data

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,8260,Erling Haaland,20,1756,19,18.415004886686802,4,3.0899876076728106,75,11,0,0,F,Manchester City,18,16.89266712218523,20.211640633642673,2.778261484578252
1,13222,Thiago,20,1680,14,13.802449688315392,1,1.5831863638013601,44,9,3,0,F S,Brentford,9,9.235436581075191,11.383689273148775,2.6555524803698063
2,11363,Antoine Semenyo,19,1710,9,7.810670031234622,3,2.4660277236253023,47,25,5,0,M,Bournemouth,8,6.288332333788276,10.328016273677349,2.9676714949309826
3,501,Danny Welbeck,19,1107,8,6.669347804039717,0,0.31755480915308,28,10,3,0,F S,Brighton,7,4.385841159150004,6.039988946169615,1.8120669340714812
4,5555,Dominic Calvert-Lewin,18,1224,8,7.4578270222991705,0,1.2653321214020252,36,12,0,0,F S,Leeds,7,6.696658169850707,8.989225076511502,1.3431714698672295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,14198,Shea Lacey,1,2,0,0.01579156517982483,0,0,1,0,0,0,S,Manchester United,0,0.01579156517982483,0.01579156517982483,0
481,14219,Mohamadou Kanté,3,8,0,0.06551869213581085,0,0.10989412665367126,1,1,0,0,S,West Ham,0,0.06551869213581085,0.17541281878948212,0
482,14263,Joél Drakes-Thomas,2,2,0,0,0,0,0,0,0,0,S,Crystal Palace,0,0,0.3753929138183594,0.3753929138183594
483,14266,Bendito Mantato,1,14,0,0,0,0.03647809848189354,0,1,0,0,S,Manchester United,0,0,0.12379638105630875,0.12379638105630875
484,14281,Jaydon Banel,1,7,0,0,0,0,0,0,0,0,S,Burnley,0,0,0,0

In [ ]:

# List of IDs from your data
player_ids = understat_data['id'].values #['8260', '13222', '11363'] # Haaland, Thiago, Semenyo, etc.
player_name_id = understat_data.set_index('id')['player_name']
player_name_id
all_history = []

with UnderstatClient() as understat:
    for p_id in player_ids:
        # This gets the season-by-season history for that specific ID
        history = understat.player(player=p_id).get_match_data()

        # # Add the player name back in so you know who is who
        for gw_ in history:
            gw_['understat_id'] = p_id
            gw_['understat_name'] = player_name_id[p_id]
            all_history.append(gw_)

# # Convert to a history DataFrame
history_df = pd.DataFrame(all_history)
history_df.to_csv(f'./data/understat/understat_hist_{gw}.csv', index=False)

## FPL

### GW 1

In [ ]:
all_player_gw_stats = []
for gw in range(1,21):
    player_gw_stats = pd.read_csv(f'{git_data_olbauday_base}GW{gw}/player_gameweek_stats.csv')
    player_gw_stats['round'] = gw
    all_player_gw_stats.append(player_gw_stats)

# 2. Combine all DataFrames at once (much faster than looping concat)
all_player_gw_stats = pd.concat(all_player_gw_stats, ignore_index=True)

all_teams = []
for gw in range(1,21):
    team_stats = pd.read_csv(f'{git_data_olbauday_base}GW{gw}/teams.csv')
    team_stats['round'] = gw
    all_teams.append(team_stats)

all_team_stats = pd.concat(all_teams, ignore_index=True)

all_players = []
for gw in range(1,21):
    team_stats = pd.read_csv(f'{git_data_olbauday_base}GW{gw}/players.csv')
    team_stats['round'] = gw
    all_players.append(team_stats)

players = pd.concat(all_players, ignore_index=True)

matches = []

for gw in range(1,21):
    data = requests.get(fpl_fixtures_url+str(gw)).json()

    matches = [*matches, *[{
                    'round': event['event'], 'team_id': event['id'], 'team_a': event['team_a'], 'team_h': event['team_h'],
                    'team_h_difficulty':event['team_h_difficulty'], 'team_a_difficulty':event['team_a_difficulty'], 'team_a_score': event['team_a_score'],
                    'team_h_score': event['team_h_score'], 'kickoff_time': event['kickoff_time']
                     } for event in data]]
    #     []
    # matches.append()
match_details = pd.DataFrame(matches)
match_details.to_csv(f'./data/match_details_{gw}.csv', index=False)

In [ ]:

player_gw_stats_clean = all_player_gw_stats[all_player_gw_stats['status']!= 'u']  # Remove unavailable players
player_gw_stats_clean.columns.tolist()
gw_stats_cols =  [
                    'id', 'first_name', 'second_name', 'web_name', 'now_cost',  'selected_by_percent',  'form',  'event_points', 'transfers_in_event',
                    'transfers_out_event', 'value_form', 'ep_next', 'ep_this', 'chance_of_playing_next_round', 'chance_of_playing_this_round',  'gw',
                    'total_points', 'minutes',  'goals_scored',  'assists',  'clean_sheets',  'goals_conceded', 'yellow_cards',  'red_cards',  'saves',
                    'starts',  'bonus',  'bps',  'transfers_in',  'transfers_out', 'expected_goals',  'expected_assists',  'expected_goal_involvements',
                    'expected_goals_conceded',  'influence',  'creativity',  'threat',  'ict_index',  'tackles',  'clearances_blocks_interceptions',
                    'recoveries',  'defensive_contribution',  'round',

                    # 'expected_goals_per_90', 'expected_assists_per_90', 'expected_goal_involvements_per_90',
                    # 'expected_goals_conceded_per_90', 'saves_per_90', 'clean_sheets_per_90', 'goals_conceded_per_90', 'defensive_contribution_per_90',

                    # 'status', 'news', 'news_added', 'now_cost_rank', 'now_cost_rank_type', 'selected_rank', 'selected_rank_type', 'form_rank', 'form_rank_type',
                    # 'cost_change_event', 'cost_change_event_fall', 'cost_change_start', 'cost_change_start_fall', 'value_season', 'points_per_game',
                    # 'points_per_game_rank', 'points_per_game_rank_type', 'influence_rank', 'influence_rank_type', 'creativity_rank', 'creativity_rank_type',
                    # 'threat_rank', 'threat_rank_type', 'ict_index_rank', 'ict_index_rank_type', 'corners_and_indirect_freekicks_order', 'direct_freekicks_order',
                    # 'penalties_order', 'set_piece_threat', 'corners_and_indirect_freekicks_text', 'direct_freekicks_text', 'penalties_text',  'own_goals', '
                    # penalties_saved', 'penalties_missed', 'dreamteam_count', 'starts_per_90',
                ]

player_gw_stats_clean = player_gw_stats_clean[gw_stats_cols]
player_gw_stats_clean [['chance_of_playing_this_round', 'chance_of_playing_next_round']]= player_gw_stats_clean[['chance_of_playing_this_round', 'chance_of_playing_next_round']].fillna(100)
ids_with_details = players['player_id'].unique().tolist()
player_gw_stats_clean = player_gw_stats_clean[player_gw_stats_clean['id'].isin(ids_with_details)]
player_gw_stats_clean = player_gw_stats_clean.merge(players[['player_id','team_code', 'position', 'round']], left_on=['id', 'round'], right_on=['player_id', 'round'], how='left')
player_gw_stats_clean = player_gw_stats_clean.dropna(subset=['team_code'])
team_data = all_team_stats.rename({'code': 'team_code', 'id': 'team_id', 'name':'team', 'short_name':'team_short_name', 'ep_this': 'xP', 'ep_next':'xP_next'}, axis=1)
player_gw_stats_clean = player_gw_stats_clean.merge(team_data[[
  'team_code', 'team_id', 'team', 'round', 'team_short_name', 'elo', 'strength', 'strength_overall_home', 'strength_overall_away', 'strength_attack_home', 'strength_attack_away',
    'strength_defence_home', 'strength_defence_away']], on=['round','team_code'], how='left')

# Reshape matches so every team_id has its own row per match
match_details = match_details.rename(columns={'team_id': 'match_id'})
matches_melted = match_details.melt(
    id_vars=['match_id', 'round', 'team_h_difficulty', 'team_a_difficulty', 'team_a_score', 'team_h_score', 'kickoff_time'],
    value_vars=['team_a', 'team_h'],
    var_name='side',
    value_name='team_id'
)

player_match_df = player_gw_stats_clean.merge(matches_melted, on=['team_id', 'round'], how='left')
player_match_df

,id,first_name,second_name,web_name,now_cost,selected_by_percent,form,event_points,transfers_in_event,transfers_out_event,...,strength_attack_away,strength_defence_home,strength_defence_away,match_id,team_h_difficulty,team_a_difficulty,team_a_score,team_h_score,kickoff_time,side
0,1,David,Raya Martín,Raya,6.0,36.9,3.2,10,418466,56691,...,1350,1290,1300,9,4,3,1,0,2025-08-17T15:30:00Z,team_a
1,2,Kepa,Arrizabalaga Revuelta,Arrizabalaga,4.1,0.4,0.0,0,793,2256,...,1350,1290,1300,9,4,3,1,0,2025-08-17T15:30:00Z,team_a
2,4,Tommy,Setford,Setford,3.9,0.2,0.0,0,2397,1906,...,1350,1290,1300,9,4,3,1,0,2025-08-17T15:30:00Z,team_a
3,5,Gabriel,dos Santos Magalhães,Gabriel,6.2,14.0,0.0,6,5927,342245,...,1350,1290,1300,9,4,3,1,0,2025-08-17T15:30:00Z,team_a
4,6,William,Saliba,Saliba,6.0,10.3,0.5,9,25445,160545,...,1350,1290,1300,9,4,3,1,0,2025-08-17T15:30:00Z,team_a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12241,646,João Victor,Gomes da Silva,Gomes,5.3,0.1,2.5,1,175,239,...,1050,1090,1120,200,2,2,0,3,2026-01-03T15:00:00Z,team_h
12242,695,Jackson,Tchatchoua,Tchatchoua,4.4,0.0,1.5,5,89,43,...,1050,1090,1120,200,2,2,0,3,2026-01-03T15:00:00Z,team_h
12243,709,Ladislav,Krejcí,Krejčí,4.5,0.1,3.2,6,818,266,...,1050,1090,1120,200,2,2,0,3,2026-01-03T15:00:00Z,team_h
12244,777,Temple,Ojinnaka,Ojinnaka,4.5,0.0,0.0,0,40,10,...,1050,1090,1120,200,2,2,0,3,2026-01-03T15:00:00Z,team_h
12245,778,Ethan,Sutherland,Sutherland,4.5,0.0,0.0,0,59,16,...,1050,1090,1120,200,2,2,0,3,2026-01-03T15:00:00Z,team_h

In [ ]:
unique_players = player_gw_stats_clean['id'].unique()

player_api_data = []

for pid in unique_players:
    # Fetch from API
    response = requests.get(f'{player_summary}{pid}/')
    data = response.json()  # assuming JSON response
    history_data = data['history']

    player_api_data = [*player_api_data, *history_data]

pd.DataFrame(player_api_data).rename({'element': 'id'}, axis=1).to_csv(f'./data/player_summary_{gw}.csv', index=False)

In [ ]:
player_api_details = pd.read_csv(f'./data/player_summary_{gw}.csv')
understat_data = pd.read_csv(f'./data/understat/understat_hist_{gw}.csv')
understat_data = understat_data[understat_data['season'] == 2025]

# ids availabe from the api
live_ids = player_api_details['id'].unique().tolist()
player_match_df_ = player_match_df[player_match_df['id'].isin(live_ids)].copy()

fpl_understat_map = master_fpl_understat_map[(
                                                ~master_fpl_understat_map['25-26'].isna())
                                                & ~(master_fpl_understat_map['understat'].isna())].rename({'25-26': 'fpl_id', 'understat':'understat_id'}, axis=1)

player_match_df_['date'] = pd.to_datetime(player_match_df_['kickoff_time']).dt.date
understat_data['date'] = pd.to_datetime(understat_data['date']).dt.date
player_gw_stats_full = player_match_df_.merge(player_api_details[['id', 'round', 'selected', 'transfers_balance', 'was_home', 'value', 'opponent_team']],
                                            on=['round', 'id'],
                                            how='left')

player_gw_stats_full = player_gw_stats_full.rename(columns={'player_id':'fpl_id'}).drop('id', axis=1)

player_gw_stats_full = player_gw_stats_full[player_gw_stats_full['fpl_id'].isin(fpl_understat_map['fpl_id'].unique().tolist())]

understat_data = understat_data.merge(fpl_understat_map[['fpl_id', 'understat_id']], on='understat_id', how='left').dropna()
player_gw_stats_full = player_gw_stats_full.merge(fpl_understat_map[['fpl_id', 'understat_id']],
                                                  on='fpl_id',
                                                  how='left')

player_gw_stats_full['full_name'] = (player_gw_stats_full['first_name'] + ' ' + player_gw_stats_full['second_name']).str.strip()

player_data = player_gw_stats_full.merge(understat_data[[
                                'goals', 'shots', 'xG','h_team', 'a_team',
                                'h_goals', 'a_goals', 'date', 'season', 'roster_id', 'xA',
                                'key_passes', 'npg', 'npxG', 'xGChain', 'xGBuildup',
                                'understat_id', 'understat_name', 'fpl_id']],
                                on=['date', 'fpl_id', 'understat_id'],
                                how='left'
                                )

player_data = player_data.rename(columns={'ep_this': 'xP', 'ep_next': 'xP_next'})

player_data.to_csv('./data/player_data.csv', index=False)

### Add Odds

In [ ]:
player_data = pd.read_csv('./data/player_data.csv', low_memory=False)
player_data_clean = player_data.dropna()
# Load the current season's data directly from the source
season = "2526" # Change this for historical seasons
url = f"https://www.football-data.co.uk/mmz4281/{season}/E0.csv"

# It's good practice to use a custom User-Agent to avoid blocks
odds_data = pd.read_csv(url, low_memory=False)

# 1. Clean up dates in betting data
odds_data['Date'] = pd.to_datetime(odds_data['Date'], dayfirst=True).dt.date

# 2. Extract key columns (B365H = Bet365 Home Odds, B365D = Draw, B365A = Away)
odds_subset = odds_data[['Date', 'HomeTeam', 'AwayTeam', 'B365H', 'B365D', 'B365A']].copy()
odds_subset = odds_subset.rename(columns={'Date': 'date'})

def add_odds(row):
    win = round(1/row['B365H'], 5)
    draw = round(1/row['B365D'], 5)
    lose = round(1/row['B365A'], 5)

    # Normalize the probabilities (to make the probabilities sum to 100%)
    sum_percent = win + draw + lose
    win_prob = round(win/sum_percent, 3)
    draw_prob = round(draw/sum_percent, 3)
    lose_prob = round(lose/sum_percent, 3)

    return pd.Series([win_prob, draw_prob, lose_prob])

odds_subset[['win_prob', 'draw_prob', 'lose_prob']] = odds_subset.apply(add_odds, axis=1)

# Make sure the names match in the player_data df and odds_subset df
team_map = {
    'Bournemouth': 'Bournemouth',
    'Newcastle': 'Newcastle',
    'Fulham': 'Fulham',
    'West Ham': 'West Ham',
    'Burnley': 'Burnley',
    'Man City': 'Man City',
    'Crystal Palace': 'Crystal Palace',
    'Brentford': 'Brentford',
    'Arsenal': 'Arsenal',
    'Everton': 'Everton',
    'Chelsea': 'Chelsea',
    'Tottenham': 'Spurs',
    'Wolves': 'Wolves',
    'Aston Villa': 'Aston Villa',
    'Sunderland': 'Sunderland',
    'Leeds': 'Leeds',
    "Nott'm Forest": "Nott'm Forest",
    'Brighton': 'Brighton',
    'Man United': 'Man Utd',
    'Liverpool': 'Liverpool'
}

odds_subset['HomeTeam'] = odds_subset['HomeTeam'].map(team_map)
odds_subset['AwayTeam'] = odds_subset['AwayTeam'].map(team_map)

odds_melted = odds_subset.melt(
    id_vars=['date','B365H', 'B365D', 'B365A', 'win_prob', 'draw_prob', 'lose_prob'],
    value_vars=['HomeTeam', 'AwayTeam'],
    var_name='side',
    value_name='team'
)

odds_melted['date'] = odds_melted['date'].astype(str)

player_data_odds = player_data_clean.merge(odds_melted[['date', 'win_prob', 'draw_prob', 'lose_prob','team']],
                  on=['date', 'team'],
                  how='left'
                  )

# 1. Sort by player and round to ensure the sequence is correct
player_data_odds = player_data_odds.sort_values(['fpl_id', 'round'])

# 2. Group by player and apply the difference
player_data_odds['ownership_change'] = player_data_odds.groupby('fpl_id')['selected'].diff().fillna(0)
player_data_odds['pts_bonus'] = player_data_odds['total_points'] - player_data_odds['bonus']

def ownership_change(row):
    net_transfers = row['transfers_in'] - row['transfers_out']
    total_transfers = row['transfers_in'] + row['transfers_out']
    net_transfers_pct = net_transfers / total_transfers if total_transfers != 0 else 0

    return net_transfers_pct

player_data_odds['percenatge_net_transfers'] = player_data_odds.apply(ownership_change, axis=1)


player_data_odds.to_csv('./data/final_player_data.csv')

### Roll values

In [18]:
player_data_odds = pd.read_csv('./data/final_player_data.csv')

rolling_features = [
    'creativity', 'influence', 'threat', 'minutes',  'pts_bonus', 'total_points',
    'expected_goals', 'expected_assists', 'xP',
    'expected_goals_conceded', 'goals_conceded', 'goals_scored',
    'shots', 'key_passes', 'npg', 'npxG','goals', 'shots', 'xG','xA',
    'saves', 'starts', 'yellow_cards', 'red_cards','assists', 'clean_sheets',

    'value', 'ict_index', 'selected', 'transfers_in', 'transfers_out',
    'ownership_change', 'percenatge_net_transfers',
    'xGChain', 'xGBuildup', 'expected_goal_involvements', 'form',
    'clearances_blocks_interceptions', 'tackles', 'recoveries', 'defensive_contribution', 'selected_by_percent',
    'goals_conceded','goals_scored',

    'strength', 'strength_overall_home', 'strength_overall_away',
    'strength_attack_home', 'strength_attack_away', 'strength_defence_home', 'strength_defence_away',
]

player_df = player_data_odds.copy()


## Cater for the mssing rounds before rolling
# 1. Get all unique players and all unique rounds
all_players = player_df['fpl_id'].unique()
all_rounds = range(player_df['round'].min(), player_df['round'].max() + 1)

# 2. Create a MultiIndex of every player x every round
multi_idx = pd.MultiIndex.from_product([all_players, all_rounds], names=['fpl_id', 'round'])

# 3. Reindex the dataframe
# This inserts "empty" rows for missing player/round combinations
player_df_complete = player_df.set_index(['fpl_id', 'round']).reindex(multi_idx).reset_index()

# Fill statistical columns with 0
# stat_columns = ['goals_scored', 'goals_conceded', 'expected_goals_conceded']
player_df_complete = player_df_complete.fillna(0)

# Sort to ensure chronological order for the rolling window
player_df_complete = player_df_complete.sort_values(['fpl_id', 'round'])

# Averagae values
for col in rolling_features:
    # The rolling window now spans actual calendar rounds
    player_df_complete[f'{col}_1'] = player_df_complete.groupby(['fpl_id'])[col].shift(1).rolling(1, min_periods=1).mean().reset_index(0, drop=True)
    player_df_complete[f'{col}_3'] = player_df_complete.groupby(['fpl_id'])[col].shift(1).rolling(3, min_periods=3).mean().reset_index(0, drop=True)
    player_df_complete[f'{col}_5'] = player_df_complete.groupby(['fpl_id'])[col].shift(1).rolling(5, min_periods=5).mean().reset_index(0, drop=True)

    player_df_complete = player_df_complete.copy()

player_df_complete = player_df_complete[player_df_complete['team_id'] != 0]


# Add opponent details
# Aggregate player data so there is exactly ONE row per team per round
team_lookup = player_df_complete.groupby(['team', 'round']).agg({
    'clean_sheets': 'max',
    'elo': 'first', # Elo is usually the same for all players on the team
    'strength': 'first'
}).reset_index()

# Rename columns to 'opponent_...' so they don't clash with the player's own stats
team_lookup.columns = ['opponent_team_name', 'round'] + [f'opp_{col}' for col in team_lookup.columns if col not in ['team', 'round']]

# check your column name for who the player is playing AGAINST (e.g., 'opponent')
player_df_final = player_df_complete.merge(
    team_lookup,
    left_on=['team', 'round'],  # 'opponent' is the ID of the team they face
    right_on=['opponent_team_name', 'round'],
    how='left'
)

# numeric_cols = player_df_final.select_dtypes(include=['number']).columns

# # Tier 1: Player-level mean
# player_df_final[numeric_cols] = player_df_final.groupby('fpl_id')[numeric_cols].transform(lambda x: x.fillna(x.mean()))

# # Tier 2: Team-level mean (for players with NO personal stats yet)
# player_df_final[numeric_cols] = player_df_final.groupby(['team', 'round'])[numeric_cols].transform(lambda x: x.fillna(x.mean()))

# # Tier 3: Global constant (The safety net)
# player_df_final[numeric_cols] = player_df_final[numeric_cols].fillna(0)


player_df_final.to_csv('./data/rolled_player_data.csv', index=False)
player_df_final

,fpl_id,round,Unnamed: 0,first_name,second_name,web_name,now_cost,selected_by_percent,form,event_points,...,strength_defence_home_1,strength_defence_home_3,strength_defence_home_5,strength_defence_away_1,strength_defence_away_3,strength_defence_away_5,opponent_team_name,opp_clean_sheets,opp_elo,opp_strength
0,1.0,1,0.0,David,Raya Martín,Raya,6.0,36.9,3.2,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Arsenal,1.0,2037.0,4.0
1,1.0,2,293.0,David,Raya Martín,Raya,5.5,21.5,8.0,6.0,...,1290.0,NaN,NaN,1300.0,NaN,NaN,Arsenal,1.0,2037.0,4.0
2,1.0,3,603.0,David,Raya Martín,Raya,5.5,21.8,6.0,2.0,...,1290.0,NaN,NaN,1300.0,NaN,NaN,Arsenal,1.0,2037.0,4.0
3,1.0,4,905.0,David,Raya Martín,Raya,5.5,23.5,6.0,6.0,...,1290.0,1290.000000,NaN,1300.0,1300.000000,NaN,Arsenal,1.0,2037.0,4.0
4,1.0,5,1209.0,David,Raya Martín,Raya,5.5,24.0,4.0,2.0,...,1290.0,1290.000000,NaN,1300.0,1300.000000,NaN,Arsenal,0.0,2037.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6022,737.0,14,4112.0,Jonah,Kusi-Asare,Kusi-Asare,4.5,0.1,0.2,1.0,...,0.0,0.000000,224.0,0.0,0.000000,224.0,Fulham,0.0,1776.0,3.0
6023,737.0,17,4980.0,Jonah,Kusi-Asare,Kusi-Asare,4.5,0.1,0.4,1.0,...,0.0,366.666667,220.0,0.0,373.333333,224.0,Fulham,1.0,1785.0,3.0
6024,737.0,20,5879.0,Jonah,Kusi-Asare,Kusi-Asare,4.5,0.1,0.3,1.0,...,0.0,366.666667,220.0,0.0,373.333333,224.0,Fulham,0.0,1798.0,3.0
6025,739.0,17,5020.0,Divine,Mukasa,Mukasa,4.4,0.0,0.2,1.0,...,0.0,0.000000,0.0,0.0,0.000000,0.0,Man City,1.0,1998.0,4.0
6026,744.0,10,2845.0,Nehemiah,Oriola,Oriola,4.5,0.0,0.3,1.0,...,0.0,0.000000,0.0,0.0,0.000000,0.0,Brighton,1.0,1832.0,3.0

# Current game week

## Get Odds from WilliamHill

In [207]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import time

# Setup Driver (Adding options for stability)
options = webdriver.EdgeOptions()
# options.add_argument("--headless") # Uncomment to run without a window
driver = webdriver.Edge(options=options)

premLeague = "https://sports.williamhill.com/betting/en-gb/football/competitions/OB_TY295/English-Premier-League/matches/OB_MGMB/Match-Betting"
driver.get(premLeague)

# Explicit Wait: Wait up to 10 seconds for the match rows to appear
wait = WebDriverWait(driver, 10)
wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "article.sp-o-market--default")))

matches = driver.find_elements(By.CSS_SELECTOR, "article.sp-o-market--default")
# details = pd.DataFrame(columns=['team_h', 'team_h', 'win_prob', 'draw_prob', 'lose_prob'])
odds_list = []
for match in matches:
    try:
        # 1. Extract teams
        teams_text = match.find_element(By.CSS_SELECTOR, 'main.sp-o-market__title span').text
        if ' v ' not in teams_text: continue

        h_team_name = teams_text.split(' v ')[0]
        a_team_name = teams_text.split(' v ')[1]

        # 2. Extract odds
        odds_els = match.find_elements(By.CSS_SELECTOR, 'section.sp-o-market__buttons .sp-betbutton > span')

        if len(odds_els) < 3: continue

        decimal_odds = []
        for btn in odds_els:
            text = btn.text.strip()
            if text == 'EVS' or text == '1/1':
                decimal_odds.append(2.0)
            elif '/' in text:
                n, d = map(int, text.split('/'))
                decimal_odds.append((n / d) + 1)
            else:
                decimal_odds.append(float(text))

        # 3. Probability Calculation
        h_raw = 1 / decimal_odds[0]
        d_raw = 1 / decimal_odds[1]
        a_raw = 1 / decimal_odds[2]

        margin_total = h_raw + d_raw + a_raw

        # print('-----------------------------------------------------')
        # 4. Append to DataFrame
        match_row = {
            'team_h_name': h_team_name,
            'team_a_name': a_team_name,
            'win_prob': round(h_raw / margin_total, 3),
            'draw_prob':round(d_raw / margin_total, 3),
            'lose_prob': round(a_raw / margin_total, 3)
        }
        odds_list.append(match_row)
        # print(match_row)

    except Exception as e:
        print(f"Skipping a match due to error: {e}")


odds_details = pd.DataFrame(odds_list)

driver.quit()

odds_details.to_csv(f'./data/odds_{gw}.csv', index=False)

odds_details

          team_h_name     team_a_name  win_prob  draw_prob  lose_prob
0         Bournemouth       Tottenham     0.436      0.269      0.295
1           Brentford      Sunderland     0.515      0.265      0.221
2      Crystal Palace     Aston Villa     0.307      0.283      0.409
3             Everton          Wolves     0.531      0.273      0.196
4              Fulham         Chelsea     0.282      0.274      0.444
5            Man City        Brighton     0.664      0.194      0.143
6             Burnley         Man Utd     0.194      0.246      0.560
7           Newcastle           Leeds     0.556      0.251      0.193
8             Arsenal       Liverpool     0.586      0.230      0.184
9             Man Utd        Man City     0.236      0.236      0.527
10            Chelsea       Brentford     0.579      0.234      0.187
11              Leeds          Fulham     0.417      0.296      0.287
12          Liverpool         Burnley     0.761      0.155      0.085
13         Sunderland  Crystal Palace     0.328      0.306      0.367
14          Tottenham        West Ham     0.555      0.244      0.201
15  Nottingham Forest         Arsenal     0.168      0.237      0.596
16             Wolves       Newcastle     0.213      0.246      0.541
17        Aston Villa         Everton     0.518      0.267      0.215
18           Brighton     Bournemouth     0.498      0.246      0.256

## FPL Live Data

In [ ]:

# 'https://fantasy.premierleague.com/api/element-summary/21'
    # 'round', 'web_name', 'position',


# 'https://fantasy.premierleague.com/api/fixtures/?event=21'
    # 'team_h_difficulty', 'team_a_difficulty', 'opponent_team', 'was_home',

# https://fantasy.premierleague.com/api/bootstrap-static/
    # elements
        # 'fpl_id',
        # chance_of_playing_next_round', 'chance_of_playing_this_round'
        # 'xP_next', 'xP',
        # 'form', 'value_form', 'value',  ',
        # 'selected_by_percent', 'transfers_in', 'transfers_out',  'selected', 'transfers_balance', 'ownership_change', 'percenatge_net_transfers',
        # 'influence', 'creativity', 'threat', 'ict_index',
    # teams
        # 'strength','strength_overall_home', 'strength_overall_away', 'strength_attack_home', 'strength_attack_away',
        # 'strength_defence_home', 'strength_defence_away',  'team_id', 'team',

# http://api.clubelo.com/2026-01-06
    # 'elo'

# WilliamHill
    # 'win_prob', 'draw_prob', 'lose_prob',

In [ ]:
current_player_summary = requests.get(f'https://fantasy.premierleague.com/api/bootstrap-static/').json()
events = pd.DataFrame(requests.get('https://fantasy.premierleague.com/api/fixtures/?event=21').json())
elo_df = pd.read_csv('http://api.clubelo.com/2026-01-06')

In [240]:
current_player_summary['elements']

[{'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': None,
  'chance_of_playing_this_round': None,
  'code': 154561,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': 5,
  'cost_change_start_fall': -5,
  'dreamteam_count': 1,
  'element_type': 1,
  'ep_next': '3.3',
  'ep_this': '3.8',
  'event_points': 1,
  'first_name': 'David',
  'form': '2.8',
  'id': 1,
  'in_dreamteam': False,
  'news': '',
  'news_added': None,
  'now_cost': 60,
  'photo': '154561.jpg',
  'points_per_game': '4.0',
  'removed': False,
  'second_name': 'Raya Martín',
  'selected_by_percent': '33.6',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 80,
  'transfers_in': 3299405,
  'transfers_in_event': 26366,
  'transfers_out': 1713405,
  'transfers_out_event': 198981,
  'value_form': '0.5',
  'value_season': '13.3',
  'web_name': 'Raya',
  'region': 200,
  'team_join_date': '2024-07-04',
  'birth_date': '1995-09-15',
  'has_temporary_code': False,
  'opta_code': 'p154561',
  'minutes': 1800,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 9,
  'goals_conceded': 14,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 1,
  'red_cards': 0,
  'saves': 32,
  'bonus': 4,
  'bps': 329,
  'influence': '315.8',
  'creativity': '20.3',
  'threat': '0.0',
  'ict_index': '33.7',
  'clearances_blocks_interceptions': 15,
  'recoveries': 164,
  'tackles': 0,
  'defensive_contribution': 0,
  'starts': 20,
  'expected_goals': '0.00',
  'expected_assists': '0.04',
  'expected_goal_involvements': '0.04',
  'expected_goals_conceded': '15.07',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'influence_rank': 101,
  'influence_rank_type': 15,
  'creativity_rank': 356,
  'creativity_rank_type': 3,
  'threat_rank': 783,
  'threat_rank_type': 91,
  'ict_index_rank': 251,
  'ict_index_rank_type': 15,
  'expected_goals_per_90': 0.0,
  'saves_per_90': 1.6,
  'expected_assists_per_90': 0.0,
  'expected_goal_involvements_per_90': 0.0,
  'expected_goals_conceded_per_90': 0.75,
  'goals_conceded_per_90': 0.7,
  'now_cost_rank': 86,
  'now_cost_rank_type': 1,
  'form_rank': 144,
  'form_rank_type': 13,
  'points_per_game_rank': 80,
  'points_per_game_rank_type': 5,
  'selected_rank': 5,
  'selected_rank_type': 1,
  'starts_per_90': 1.0,
  'clean_sheets_per_90': 0.45,
  'defensive_contribution_per_90': 0.0},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': None,
  'chance_of_playing_this_round': None,
  'code': 109745,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': -4,
  'cost_change_start_fall': 4,
  'dreamteam_count': 0,
  'element_type': 1,
  'ep_next': '0.5',
  'ep_this': '1.0',
  'event_points': 0,
  'first_name': 'Kepa',
  'form': '0.0',
  'id': 2,
  'in_dreamteam': False,
  'news': '',
  'news_added': None,
  'now_cost': 41,
  'photo': '109745.jpg',
  'points_per_game': '0.0',
  'removed': False,
  'second_name': 'Arrizabalaga Revuelta',
  'selected_by_percent': '0.4',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 0,
  'transfers_in': 12152,
  'transfers_in_event': 276,
  'transfers_out': 71506,
  'transfers_out_event': 726,
  'value_form': '0.0',
  'value_season': '0.0',
  'web_name': 'Arrizabalaga',
  'region': 200,
  'team_join_date': '2025-07-01',
  'birth_date': '1994-10-03',
  'has_temporary_code': False,
  'opta_code': 'p109745',
  'minutes': 0,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 0,
  'goals_conceded': 0,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 0,
  'red_cards': 0,
  'saves': 0,
  'bonus': 0,
  'bps': 0,
  'influence': '0.0',
  'creativity': '0.0',
  'threat': '0.0',
  'ict_index': '0.0',
  'clearances_blocks_interceptions': 0,
  'recoveries': 0,
  'tackles': 0,
  'defensive_contribution': 0,
  'starts': 0,
  'expected_goals': '0.00',
  'expected_assists': '0.00',
  'expected_goal_involvements': '0.00',
  'expected_goals_conceded': '0.00',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'influence_rank': 591,
  'influence_rank_type': 81,
  'creativity_rank': 585,
  'creativity_rank_type': 70,
  'threat_rank': 551,
  'threat_rank_type': 55,
  'ict_index_rank': 596,
  'ict_index_rank_type': 81,
  'expected_goals_per_90': 0,
  'saves_per_90': 0,
  'expected_assists_per_90': 0,
  'expected_goal_involvements_per_90': 0,
  'expected_goals_conceded_per_90': 0,
  'goals_conceded_per_90': 0,
  'now_cost_rank': 636,
  'now_cost_rank_type': 38,
  'form_rank': 535,
  'form_rank_type': 76,
  'points_per_game_rank': 602,
  'points_per_game_rank_type': 81,
  'selected_rank': 269,
  'selected_rank_type': 36,
  'starts_per_90': 0,
  'clean_sheets_per_90': 0,
  'defensive_contribution_per_90': 0},
 {'can_transact': True,
  'can_select': False,
  'chance_of_playing_next_round': 0,
  'chance_of_playing_this_round': 0,
  'code': 463748,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': 0,
  'cost_change_start_fall': 0,
  'dreamteam_count': 0,
  'element_type': 1,
  'ep_next': '0.0',
  'ep_this': '0.0',
  'event_points': 0,
  'first_name': 'Karl',
  'form': '0.0',
  'id': 3,
  'in_dreamteam': False,
  'news': 'Has joined Werder Bremen on loan for the rest of the season.',
  'news_added': '2025-08-26T13:44:02.357864Z',
  'now_cost': 40,
  'photo': '463748.jpg',
  'points_per_game': '0.0',
  'removed': False,
  'second_name': 'Hein',
  'selected_by_percent': '0.2',
  'special': False,
  'squad_number': None,
  'status': 'u',
  'team': 1,
  'team_code': 3,
  'total_points': 0,
  'transfers_in': 5545,
  'transfers_in_event': 0,
  'transfers_out': 46345,
  'transfers_out_event': 252,
  'value_form': '0.0',
  'value_season': '0.0',
  'web_name': 'Hein',
  'region': 67,
  'team_join_date': '2020-10-28',
  'birth_date': '2002-04-13',
  'has_temporary_code': False,
  'opta_code': 'p463748',
  'minutes': 0,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 0,
  'goals_conceded': 0,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 0,
  'red_cards': 0,
  'saves': 0,
  'bonus': 0,
  'bps': 0,
  'influence': '0.0',
  'creativity': '0.0',
  'threat': '0.0',
  'ict_index': '0.0',
  'clearances_blocks_interceptions': 0,
  'recoveries': 0,
  'tackles': 0,
  'defensive_contribution': 0,
  'starts': 0,
  'expected_goals': '0.00',
  'expected_assists': '0.00',
  'expected_goal_involvements': '0.00',
  'expected_goals_conceded': '0.00',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'influence_rank': 552,
  'influence_rank_type': 71,
  'creativity_rank': 546,
  'creativity_rank_type': 60,
  'threat_rank': 511,
  'threat_rank_type': 45,
  'ict_index_rank': 557,
  'ict_index_rank_type': 71,
  'expected_goals_per_90': 0,
  'saves_per_90': 0,
  'expected_assists_per_90': 0,
  'expected_goal_involvements_per_90': 0,
  'expected_goals_conceded_per_90': 0,
  'goals_conceded_per_90': 0,
  'now_cost_rank': 664,
  'now_cost_rank_type': 53,
  'form_rank': 492,
  'form_rank_type': 66,
  'points_per_game_rank': 563,
  'points_per_game_rank_type': 71,
  'selected_rank': 358,
  'selected_rank_type': 52,
  'starts_per_90': 0,
  'clean_sheets_per_90': 0,
  'defensive_contribution_per_90': 0},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': None,
  'chance_of_playing_this_round': None,
  'code': 551221,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': -1,
  'cost_change_start_fall': 1,
  'dreamteam_count': 0,
  'element_type': 1,
  'ep_next': '0.5',
  'ep_this': '1.0',
  'event_points': 0,
  'first_name': 'Tommy',
  'form': '0.0',
  'id': 4,
  'in_dreamteam': False,
  'news': '',
  'news_added': None,
  'now_cost': 39,
  'photo': '551221.jpg',
  'points_per_game': '0.0',
  'removed': False,
  'second_name': 'Setford',
  'selected_by_percent': '0.3',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 0,
  'transfers_in': 31075,
  'transfers_in_event': 1173,
  'transfers_out': 26516,
  'transfers_out_event': 1161,
  'value_form': '0.0',
  'value_season': '0.0',
  'web_name': 'Setford',
  'region': 241,
  'team_join_date': '2024-07-24',
  'birth_date': '2006-03-13',
  'has_temporary_code': False,
  'opta_code': 'p551221',
  'minutes': 0,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 0,
  'goals_conceded': 0,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 0,
  'red_cards': 0,
  'saves': 0,
  'bonus': 0,
  'bps': 0,
  'influence': '0.0',
  'creativity': '0.0',
  'threat': '0.0',
  'ict_index': '0.0',
  'clearances_blocks_interceptions': 0,
  'recoveries': 0,
  'tackles': 0,
  'defensive_contribution': 0,
  'starts': 0,
  'expected_goals': '0.00',
  'expected_assists': '0.00',
  'expected_goal_involvements': '0.00',
  'expected_goals_conceded': '0.00',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'influence_rank': 522,
  'influence_rank_type': 55,
  'creativity_rank': 514,
  'creativity_rank_type': 42,
  'threat_rank': 477,
  'threat_rank_type': 27,
  'ict_index_rank': 527,
  'ict_index_rank_type': 55,
  'expected_goals_per_90': 0,
  'saves_per_90': 0,
  'expected_assists_per_90': 0,
  'expected_goal_involvements_per_90': 0,
  'expected_goals_conceded_per_90': 0,
  'goals_conceded_per_90': 0,
  'now_cost_rank': 751,
  'now_cost_rank_type': 88,
  'form_rank': 461,
  'form_rank_type': 50,
  'points_per_game_rank': 533,
  'points_per_game_rank_type': 55,
  'selected_rank': 332,
  'selected_rank_type': 46,
  'starts_per_90': 0,
  'clean_sheets_per_90': 0,
  'defensive_contribution_per_90': 0},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': 100,
  'chance_of_playing_this_round': 100,
  'code': 226597,
  'cost_change_event': 1,
  'cost_change_event_fall': -1,
  'cost_change_start': 6,
  'cost_change_start_fall': -6,
  'dreamteam_count': 4,
  'element_type': 2,
  'ep_next': '5.5',
  'ep_this': '6.0',
  'event_points': 9,
  'first_name': 'Gabriel',
  'form': '5.0',
  'id': 5,
  'in_dreamteam': True,
  'news': '',
  'news_added': '2025-11-17T12:00:07.436586Z',
  'now_cost': 66,
  'photo': '226597.jpg',
  'points_per_game': '7.6',
  'removed': False,
  'second_name': 'dos Santos Magalhães',
  'selected_by_percent': '28.9',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 106,
  'transfers_in': 6017019,
  'transfers_in_event': 790709,
  'transfers_out': 4918362,
  'transfers_out_event': 16770,
  'value_form': '0.8',
  'value_season': '16.1',
  'web_name': 'Gabriel',
  'region': 30,
  'team_join_date': '2020-09-01',
  'birth_date': '1997-12-19',
  'has_temporary_code': False,
  'opta_code': 'p226597',
  'minutes': 1175,
  'goals_scored': 3,
  'assists': 2,
  'clean_sheets': 8,
  'goals_conceded': 7,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 1,
  'red_cards': 0,
  'saves': 0,
  'bonus': 16,
  'bps': 337,
  'influence': '421.8',
  'creativity': '65.7',
  'threat': '146.0',
  'ict_index': '63.2',
  'clearances_blocks_interceptions': 103,
  'recoveries': 18,
  'tackles': 14,
  'defensive_contribution': 117,
  'starts': 13,
  'expected_goals': '1.42',
  'expected_assists': '0.71',
  'expected_goal_involvements': '2.13',
  'expected_goals_conceded': '8.59',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'influence_rank': 37,
  'influence_rank_type': 16,
  'creativity_rank': 260,
  'creativity_rank_type': 78,
  'threat_rank': 124,
  'threat_rank_type': 20,
  'ict_index_rank': 107,
  'ict_index_rank_type': 33,
  'expected_goals_per_90': 0.11,
  'saves_per_90': 0.0,
  'expected_assists_per_90': 0.05,
  'expected_goal_involvements_per_90': 0.16,
  'expected_goals_conceded_per_90': 0.66,
  'goals_conceded_per_90': 0.54,
  'now_cost_rank': 48,
  'now_cost_rank_type': 1,
  'form_rank': 36,
  'form_rank_type': 10,
  'points_per_game_rank': 2,
  'points_per_game_rank_type': 1,
  'selected_rank': 9,
  'selected_rank_type': 2,
  'starts_per_90': 1.0,
  'clean_sheets_per_90': 0.61,
  'defensive_contribution_per_90': 8.96},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': 100,
  'chance_of_playing_this_round': 100,
  'code': 462424,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': -1,
  'cost_change_start_fall': 1,
  'dreamteam_count': 0,
  'element_type': 2,
  'ep_next': '3.1',
  'ep_this': '3.6',
  'event_points': 1,
  'first_name': 'William',
  'form': '2.6',
  'id': 6,
  'in_dreamteam': False,
  'news': '',
  'news_added': '2025-11-30T22:30:08.957329Z',
  'now_cost': 59,
  'photo': '462424.jpg',
  'points_per_game': '3.4',
  'removed': False,
  'second_name': 'Saliba',
  'selected_by_percent': '11.6',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 54,
  'transfers_in': 1332610,
  'transfers_in_event': 33121,
  'transfers_out': 1872630,
  'transfers_out_event': 55468,
  'value_form': '0.4',
  'value_season': '9.2',
  'web_name': 'Saliba',
  'region': 73,
  'team_join_date': '2019-07-25',
  'birth_date': '2001-03-24',
  'has_temporary_code': False,
  'opta_code': 'p462424',
  'minutes': 1264,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 6,
  'goals_conceded': 9,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 0,
  'red_cards': 0,
  'saves': 0,
  'bonus': 1,
  'bps': 260,
  'influence': '255.2',
  'creativity': '44.7',
  'threat': '22.0',
  'ict_index': '32.2',
  'clearances_blocks_interceptions': 70,
  'recoveries': 56,
  'tackles': 18,
  'defensive_contribution': 88,
  'starts': 15,
  'expected_goals': '0.29',
  'expected_assists': '0.29',
  'expected_goal_involvements': '0.58',
  'expected_goals_conceded': '10.25',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'influence_rank': 154,
  'influence_rank_type': 66,
  'creativity_rank': 307,
  'creativity_rank_type': 101,
  'threat_rank': 340,
  'threat_rank_type': 114,
  'ict_index_rank': 261,
  'ict_index_rank_type': 88,
  'expected_goals_per_90': 0.02,
  'saves_per_90': 0.0,
  'expected_assists_per_90': 0.02,
  'expected_goal_involvements_per_90': 0.04,
  'expected_goals_conceded_per_90': 0.73,
  'goals_conceded_per_90': 0.64,
  'now_cost_rank': 97,
  'now_cost_rank_type': 6,
  'form_rank': 151,
  'form_rank_type': 56,
  'points_per_game_rank': 133,
  'points_per_game_rank_type': 50,
  'selected_rank': 35,
  'selected_rank_type': 11,
  'starts_per_90': 1.07,
  'clean_sheets_per_90': 0.43,
  'defensive_contribution_per_90': 6.27},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': 0,
  'chance_of_playing_this_round': 0,
  'code': 466075,
  'cost_change_event': -1,
  'cost_change_event_fall': 1,
  'cost_change_start': 1,
  'cost_change_start_fall': -1,
  'dreamteam_count': 2,
  'element_type': 2,
  'ep_next': '0.0',
  'ep_this': '0.0',
  'event_points': 0,
  'first_name': 'Riccardo',
  'form': '1.2',
  'id': 7,
  'in_dreamteam': False,
  'news': 'Muscle injury - Unknown return date',
  'news_added': '2025-12-27T22:00:11.031357Z',
  'now_cost': 56,
  'photo': '466075.jpg',
  'points_per_game': '4.8',
  'removed': False,
  'second_name': 'Calafiori',
  'selected_by_percent': '7.1',
  'special': False,
  'squad_number': None,
  'status': 'i',
  'team': 1,
  'team_code': 3,
  'total_points': 77,
  'transfers_in': 2530198,
  'transfers_in_event': 194,
  'transfers_out': 2228208,
  'transfers_out_event': 110015,
  'value_form': '0.2',
  'value_season': '13.8',
  'web_name': 'Calafiori',
  'region': 106,
  'team_join_date': '2024-07-29',
  'birth_date': '2002-05-19',
  'has_temporary_code': False,
  'opta_code': 'p466075',
  'minutes': 1256,
  'goals_scored': 1,
  'assists': 2,
  'clean_sheets': 9,
  'goals_conceded': 7,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 5,
  'red_cards': 0,
  'saves': 0,
  'bonus': 4,
  'bps': 287,
  'influence': '222.0',
  'creativity': '104.8',
  'threat': '219.0',
  'ict_index': '54.5',
  'clearances_blocks_interceptions': 57,
  'recoveries': 57,
  'tackles': 28,
  'defensive_contribution': 85,
  'starts': 16,
  'expected_goals': '2.49',
  'expected_assists': '0.36',
  'expected_goal_involvements': '2.85',
  'expected_goals_conceded': '7.09',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'influence_rank': 179,
  'influence_rank_type': 72,
  'creativity_rank': 193,
  'creativity_rank_type': 47,
  'threat_rank': 69,
  'threat_rank_type': 4,
  'ict_index_rank': 143,
  'ict_index_rank_type': 48,
  'expected_goals_per_90': 0.18,
  'saves_per_90': 0.0,
  'expected_assists_per_90': 0.03,
  'expected_goal_involvements_per_90': 0.21,
  'expected_goals_conceded_per_90': 0.51,
  'goals_conceded_per_90': 0.5,
  'now_cost_rank': 133,
  'now_cost_rank_type': 14,
  'form_rank': 276,
  'form_rank_type': 104,
  'points_per_game_rank': 27,
  'points_per_game_rank_type': 12,
  'selected_rank': 61,
  'selected_rank_type': 21,
  'starts_per_90': 1.15,
  'clean_sheets_per_90': 0.64,
  'defensive_contribution_per_90': 6.09},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': 100,
  'chance_of_playing_this_round': 100,
  'code': 445122,
  'cost_change_event': -1,
  'cost_change_event_fall': 1,
  'cost_change_start': 8,
  'cost_change_start_fall': -8,
  'dreamteam_count': 2,
  'element_type': 2,
  'ep_next': '4.5',
  'ep_this': '5.0',
  'event_points': 3,
  'first_name': 'Jurriën',
  'form': '4.0',
  'id': 8,
  'in_dreamteam': False,
  'news': '',
  'news_added': '2025-12-27T22:00:11.070756Z',
  'now_cost': 63,
  'photo': '445122.jpg',
  'points_per_game': '5.2',
  'removed': False,
  'second_name': 'Timber',
  'selected_by_percent': '27.1',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 98,
  'transfers_in': 5369906,
  'transfers_in_event': 71013,
  'transfers_out': 2675088,
  'transfers_out_event': 239846,
  'value_form': '0.6',
  'value_season': '15.6',
  'web_name': 'J.Timber',
  'region': 152,
  'team_join_date': '2023-07-14',
  'birth_date': '2001-06-17',
  'has_temporary_code': False,
  'opta_code': 'p445122',
  'minutes': 1549,
  'goals_scored': 2,
  'assists': 4,
  'clean_sheets': 8,
  'goals_conceded': 12,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 2,
  'red_cards': 0,
  'saves': 0,
  'bonus': 7,
  'bps': 350,
  'influence': '364.0',
  'creativity': '273.5',
  'threat': '307.0',
  'ict_index': '94.7',
  'clearances_blocks_interceptions': 53,

In [257]:
teams_data = pd.DataFrame(current_player_summary['teams'])
players_data = pd.DataFrame(current_player_summary['elements'])

teams_ids = teams[['id', 'name']].rename({'id': 'team', 'name': 'team_name'}, axis=1)
teams_data = teams_data.rename({'id': 'team', 'name': 'team_name'}, axis=1)
players_data_ = players_data.merge(teams_data[[
                       'team', 'team_name', 'strength','strength_overall_home', 'strength_overall_away', 'strength_attack_home', 'strength_attack_away',
                        'strength_defence_home', 'strength_defence_away']],
                        on='team',
                        how='left'
                        )
players_data_ = players_data_.rename({'element_type': 'position', 'ep_this': 'xP', 'ep_next': 'xP_next', 'now_cost': 'value',}, axis=1)
# Get event details
events_ = events[['event', 'team_a', 'team_h', 'team_h_difficulty', 'team_a_difficulty']]

def add_team_details(row):
    team = row['team']
    event_ = events_[(events_['team_a'] == team) | (events_['team_h'] == team)]

    was_home = team == event_['team_h'].values[0]
    opponent_team = event_['team_a'].values[0] if was_home else event_['team_h'].values[0]
    event = event_['event'].values[0]

    return pd.Series([
                        event_['team_h'].values[0],
                        event_['team_a'].values[0],
                        event_['team_h_difficulty'].values[0],
                        event_['team_a_difficulty'].values[0],
                        was_home,
                        opponent_team,
                        event])

players_data_[['team_h', 'team_a', 'team_h_difficulty', 'team_a_difficulty', 'was_home', 'opponent_team', 'round']] = players_data_.apply(add_team_details, axis=1)

# Add Elo
pl_elo = elo_df[(elo_df['Country'] == 'ENG') & (elo_df['Level'] == 1)].sort_values('Elo', ascending=False)

elo_fpl_teams = {
    'Arsenal' : 'Arsenal',
    'Man City' : 'Man City',
    'Liverpool' :'Liverpool',
    'Aston Villa' : 'Aston Villa' ,
    'Chelsea' : 'Chelsea',
    'Newcastle' : 'Newcastle',
    'Brighton' : 'Brighton',
    'Man United' : 'Man Utd',
    'Brentford' : 'Brentford',
    'Tottenham' : 'Spurs',
    'Everton' : 'Everton',
    'Crystal Palace' : 'Crystal Palace',
    'Fulham' : 'Fulham',
    'Bournemouth' : 'Bournemouth',
    'Forest' : "Nott'm Forest",
    'Leeds' : 'Leeds',
    'West Ham' : 'West Ham',
    'Burnley' : 'Burnley',
    'Sunderland' : 'Sunderland',
    'Wolves' : 'Wolves'
}

pl_elo['team_name'] = pl_elo['Club'].map(elo_fpl_teams)
pl_elo = pl_elo.rename({'Elo': 'elo'}, axis=1)

players_data_ = players_data_.merge(pl_elo[['team_name', 'elo']],
                    on='team_name',
                    how='left')

# Adds odds details
odds_details = pd.read_csv('./data/odds_21.csv')
odds_details = odds_details.rename({'a_team': 'team_a_name', 'h_team': 'team_h_name'}, axis=1)

id_team_map = pd.Series(teams['name'].values, index=teams['id']).to_dict()

players_data_['team_h_name'] =  players_data_['team_h'].map(id_team_map)
players_data_['team_a_name'] =  players_data_['team_a'].map(id_team_map)

players_data_ = players_data_.merge(odds_details,
                    on=['team_h_name', 'team_a_name'],
                    how='left')
players_data_.to_csv(f'./data/player_data{gw}.csv')
players_data_ = players_data_.rename({'id': 'fpl_id', 'team': 'team_id', 'team_name': 'team'}, axis=1)

In [ ]:
players_data_[['xP', 'creativity', 'influence', 'threat', 'minutes', 'total_points',  'expected_goals', 'expected_assists', 'xP',
    'expected_goals_conceded', 'goals_conceded', 'goals_scored',
    'shots', 'key_passes', 'npg', 'npxG','goals', 'shots', 'xG','xA',
    'saves', 'starts', 'yellow_cards', 'red_cards','assists', 'clean_sheets',]]

KeyError: "['shots', 'key_passes', 'npg', 'npxG', 'goals', 'xG', 'xA'] not in index"

In [ ]:
players_data_[


    'value', 'ict_index', 'selected', 'transfers_in', 'transfers_out',
    'ownership_change', 'percenatge_net_transfers',
    'xGChain', 'xGBuildup', 'expected_goal_involvements', 'form',
    'clearances_blocks_interceptions', 'tackles', 'recoveries', 'defensive_contribution', 'selected_by_percent',
    'goals_conceded','goals_scored',

    'strength', 'strength_overall_home', 'strength_overall_away',
    'strength_attack_home', 'strength_attack_away', 'strength_defence_home', 'strength_defence_away',
]

KeyError: ('creativity', 'influence', 'threat', 'minutes', 'total_points', 'expected_goals', 'expected_assists', 'xP', 'expected_goals_conceded', 'goals_conceded', 'goals_scored', 'shots', 'key_passes', 'npg', 'npxG', 'goals', 'shots', 'xG', 'xA', 'saves', 'starts', 'yellow_cards', 'red_cards', 'assists', 'clean_sheets', 'value', 'ict_index', 'selected', 'transfers_in', 'transfers_out', 'ownership_change', 'percenatge_net_transfers', 'xGChain', 'xGBuildup', 'expected_goal_involvements', 'form', 'clearances_blocks_interceptions', 'tackles', 'recoveries', 'defensive_contribution', 'selected_by_percent', 'goals_conceded', 'goals_scored', 'strength', 'strength_overall_home', 'strength_overall_away', 'strength_attack_home', 'strength_attack_away', 'strength_defence_home', 'strength_defence_away')